### ISSUE TITLE
Processing data from different detectors (i.e. two instances of Pilatus) fails

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#104]
Get an error which looks like this

```
Traceback (most recent call last):
  File "/Applications/ccp4-7.0/lib/py2/site-packages/xia2/command_line/xia2_main.py", line 282, in run
    xinfo = xia2_main()
  File "/Applications/ccp4-7.0/lib/py2/site-packages/xia2/command_line/xia2_main.py", line 36, in xia2_main
    CommandLine = get_command_line()
  File "/Applications/ccp4-7.0/lib/py2/site-packages/xia2/Applications/xia2.py", line 121, in get_command_line
    save_datablock(os.path.join(os.getcwd(), 'xia2-datablock.json'))
  File "/Applications/ccp4-7.0/lib/py2/site-packages/xia2/Applications/xia2setup.py", line 161, in save_datablock
    datablock.append(imageset)
  File "/Applications/ccp4-7.0/lib/py2/site-packages/cctbx_project/dxtbx/datablock.py", line 36, in append
    assert(self._format_class == imageset.reader().get_format_class())
AssertionError

```

This is probably not ideal & should be resolved.

**Comment by rjgildea** [comment]
Also an issue for dials.import:
```
$ dials.import $(libtbx.find_under_build xia2_regression)/test_data/X4_wide/X4_wide_M1S4_2_000*.cbf $(libtbx.find_under_build xia2_regression)/test_data/i04_bag_training/th_8_2_000*.cbf 
DIALS 1.dev.1175-g063db8e
The following parameters have been modified:

input {
  datablock = <image files>
}


Applying input geometry in the following order:
  1. Manual geometry

Sorry: More than 1 datablock found
```
