### ISSUE TITLE
Unusual behaviour - dials.generate_mask works standalone, fails in xia2

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#117]
In one console session:

```
Free space:        118823.56 GB
Host: cs04r-sc-com99-01
Contact: xia2.support@gmail.com
XIA2 0.5.280-g98712c6
DIALS 1.dev.1313-g376ec50
CCP4 7.0.035
Command line: xia2 xinfo=automatic.xinfo
-------------------- Spotfinding SWEEP1 --------------------
Status: error "dials.generate_mask terminated with an error: see /dls/mx-scratch/gw56/Eiger/Soleil-28/xia2-subset/DEFAULT/SAD/SWEEP1/index/1_dials.generate_mask.log for more details"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
[gw56@cs04r-sc-com99-01 xia2-subset]$ cat /dls/mx-scratch/gw56/Eiger/Soleil-28/xia2-subset/DEFAULT/SAD/SWEEP1/index/1_dials.generate_mask.log
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/generate_mask.py", line 13, in <module>
    from iotbx.phil import parse
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/iotbx/phil.py", line 2, in <module>
    from cctbx import sgtbx
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/cctbx/sgtbx/__init__.py", line 2, in <module>
    from cctbx import uctbx
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/cctbx/uctbx/__init__.py", line 2, in <module>
    import cctbx.array_family.flex # import dependency
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/cctbx/array_family/flex.py", line 2, in <module>
    import scitbx.array_family.flex
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/scitbx/array_family/flex.py", line 2, in <module>
    import boost.optional # import dependency
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/boost_adaptbx/boost/optional.py", line 2, in <module>
    import boost.python
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/boost_adaptbx/boost/python.py", line 4, in <module>
    from libtbx import cpp_function_name
ImportError: cannot import name cpp_function_name
# command line:
# dials.generate_mask  'input.datablock="SWEEP1_datablock.json"' 'output.mask="1_mask.pickle"' 'output.datablock="1_SWEEP1_datablock.json"' '1_mask.phil'
```

```
[gw56@cs04r-sc-com99-01 xia2-subset]$ cd DEFAULT/SAD/SWEEP1/index/
[gw56@cs04r-sc-com99-01 index]$ ls
1_dials.generate_mask.log  1_mask.phil	SWEEP1_datablock.json
[gw56@cs04r-sc-com99-01 index]$ dials.generate_mask  'input.datablock="SWEEP1_datablock.json"' 'output.mask="1_mask.pickle"' 'output.datablock="1_SWEEP1_datablock.json"' '1_mask.phil'
The following parameters have been modified:

output {
  mask = "1_mask.pickle"
  datablock = "1_SWEEP1_datablock.json"
}
input {
  datablock = SWEEP1_datablock.json
}

Writing mask to 1_mask.pickle
Saving datablocks to 1_SWEEP1_datablock.json
```

**Comment by graeme-winter** [comment]
Can reproduce this with installed 1.5 release however get different (more helpful?) error message

```
ImportError: /dls_sw/apps/dials/dials-v1-5-0/base/lib/python2.7/lib-dynload/itertools.so: cannot open shared object file: Too many open files
```

**Comment by graeme-winter** [comment]
@Anthchirp @rjgildea any ideas?

**Comment by Anthchirp** [comment]
Opening up too many files for not good enough reasons
```
open("thaumatin_0.025trans_0.1dpf_4dps_data_000910.h5", O_RDWR) = -1 ENOENT (No such file or directory)
open("/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_data_000910.h5", O_RDONLY) = 917
open("/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_data_000911.h5", O_RDWR) = -1 EACCES (Permission denied)
open("/dls/tmp/wra62962/directories/rObJnyTO/index/thaumatin_0.025trans_0.1dpf_4dps_data_000911.h5", O_RDWR) = -1 ENOENT (No such file or directory)
open("thaumatin_0.025trans_0.1dpf_4dps_data_000911.h5", O_RDWR) = -1 ENOENT (No such file or directory)
open("/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_data_000911.h5", O_RDONLY) = 918
open("/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_data_000912.h5", O_RDWR) = -1 EACCES (Permission denied)
open("/dls/tmp/wra62962/directories/rObJnyTO/index/thaumatin_0.025trans_0.1dpf_4dps_data_000912.h5", O_RDWR) = -1 ENOENT (No such file or directory)
open("thaumatin_0.025trans_0.1dpf_4dps_data_000912.h5", O_RDWR) = -1 ENOENT (No such file or directory)
open("/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_data_000912.h5", O_RDONLY) = 919
open("/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_data_000913.h5", O_RDWR) = -1 EACCES (Permission denied)
open("/dls/tmp/wra62962/directories/rObJnyTO/index/thaumatin_0.025trans_0.1dpf_4dps_data_000913.h5", O_RDWR) = -1 ENOENT (No such file or directory)
open("thaumatin_0.025trans_0.1dpf_4dps_data_000913.h5", O_RDWR) = -1 ENOENT (No such file or directory)
open("/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_data_000913.h5", O_RDONLY) = 920
open("/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_data_000914.h5", O_RDWR) = -1 EACCES (Permission denied)
open("/dls/tmp/wra62962/directories/rObJnyTO/index/thaumatin_0.025trans_0.1dpf_4dps_data_000914.h5", O_RDWR) = -1 ENOENT (No such file or directory)
```

**Comment by Anthchirp** [comment]
leading to 
```
open("/scratch/wra62962/files/dials/modules/cctbx_project/boost_adaptbx/boost/__init__.pyc", O_RDONLY) = -1 EMFILE (Too many open files)
(..)
close(1023)                             = 0
```
when run within xia2, and just scraping below limit when run on command line.

**Comment by Anthchirp** [comment]
files are only closed on process termination, so file descriptor leak in dials?

**Comment by graeme-winter** [comment]
Can reproduce opening hundreds of files with

```
from dxtbx.datablock import DataBlockFactory
db = DataBlockFactory.from_json_file('datablock.json')
```

from imported object

**Comment by rjgildea** [comment]
Is this only specific to hdf5 files? Should probably close this issue and move to dials/dxtbx issue tracker...

**Comment by Anthchirp** [comment]
I'd keep this issue open to confirm the problem is fixed

**Comment by graeme-winter** [comment]
Testing this again now

**Comment by graeme-winter** [comment]
Hmmm problem still extant :(

**Comment by graeme-winter** [comment]
OK, just had the same issue when I tried to revisit this data set:

```
Exception C: __import__("dials_model_data_ext"): /dls/science/users/gw56/svn/cctbx/build/lib/dials_model_data_ext.so: cannot open shared object file: Too many open files
sys.path:
/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line
/home/gw56/.local/lib/python2.7/site-packages/PyCifRW-4.1-py2.7-linux-x86_64.egg
/home/gw56/.local/lib/python2.7/site-packages/ply-3.2-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/py-1.4.31-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/colorama-0.3.7-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/pytest-2.9.1-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/funcsigs-1.0.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/junit_xml-1.6-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Sphinx-1.4.4-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/imagesize-0.7.1-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/alabaster-0.7.10-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Babel-2.4.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/snowballstemmer-1.2.1-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Pygments-2.2.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Jinja2-2.9.6-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/pytz-2017.2-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/MarkupSafe-1.0-py2.7-linux-x86_64.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/numpydoc-0.5-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/PyOpenGL-3.1.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Send2Trash-1.3.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/matplotlib-2.0.0-py2.7-linux-x86_64.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/pyparsing-2.2.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/cycler-0.10.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/subprocess32-3.2.7-py2.7-linux-x86_64.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/functools32-3.2.3.post2-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/python_dateutil-2.6.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/modules/cctbx_project
/dls/science/users/gw56/svn/cctbx/modules
/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/boost_adaptbx
/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/pythonpath
/dls/science/users/gw56/svn/cctbx/build/lib
/dls/science/users/gw56/svn/cctbx/base/lib/site-python
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages
/dls/science/users/gw56/svn/cctbx/base/lib/python27.zip
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/plat-linux2
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/lib-tk
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/lib-old
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/lib-dynload
/home/gw56/.local/lib/python2.7/site-packages
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/PIL
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/wx-3.0-gtk2 (/dls/mx-scratch/gw56/Eiger/Soleil-28/thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_master.h5)
Traceback (most recent call last):
File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Applications/xia2setup_helpers.py", line 15, in get_sweep
sweeplist = SweepFactory(template, directory)
File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Sweep.py", line 38, in SweepFactory
reversephi=PhilIndex.params.xia2.settings.input.reverse_phi)
File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/__init__.py", line 84, in load_imagesets
format_kwargs=format_kwargs)
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 899, in from_filenames
format_kwargs=format_kwargs)
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 472, in __init__
format_kwargs=format_kwargs)
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 642, in _create_single_file_imageset
format_instance = format_class(abspath(filename), **format_kwargs)
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDFEigerNearlyNexus.py", line 272, in __init__
FormatHDF5.__init__(self, image_file, **kwargs)
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDF5.py", line 16, in __init__
Format.__init__(self, image_file, **kwargs)
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/Format.py", line 119, in __init__
self.setup()
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/Format.py", line 129, in setup
self._start()
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDFEigerNearlyNexus.py", line 322, in _start
self._mask = MaskFactory([detector]).mask
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/nexus.py", line 1658, in __init__
self.mask.extend(list(make_mask(handle["detectorSpecific"]["pixel_mask"])))
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/nexus.py", line 1640, in make_mask
from dials.array_family import flex
File "/dls/science/users/gw56/svn/cctbx/modules/dials/array_family/__init__.py", line 2, in <module>
import dials.model.data # import dependancy
File "/dls/science/users/gw56/svn/cctbx/modules/dials/model/data/__init__.py", line 4, in <module>
ext = boost.python.import_ext("dials_model_data_ext")
File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/boost_adaptbx/boost/python.py", line 36, in import_ext
+ ["  "+p for p in sys.path]))
ImportError: __import__("dials_model_data_ext"): /dls/science/users/gw56/svn/cctbx/build/lib/dials_model_data_ext.so: cannot open shared object file: Too many open files
sys.path:
/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line
/home/gw56/.local/lib/python2.7/site-packages/PyCifRW-4.1-py2.7-linux-x86_64.egg
/home/gw56/.local/lib/python2.7/site-packages/ply-3.2-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/py-1.4.31-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/colorama-0.3.7-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/pytest-2.9.1-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/funcsigs-1.0.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/junit_xml-1.6-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Sphinx-1.4.4-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/imagesize-0.7.1-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/alabaster-0.7.10-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Babel-2.4.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/snowballstemmer-1.2.1-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Pygments-2.2.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Jinja2-2.9.6-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/pytz-2017.2-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/MarkupSafe-1.0-py2.7-linux-x86_64.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/numpydoc-0.5-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/PyOpenGL-3.1.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/Send2Trash-1.3.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/matplotlib-2.0.0-py2.7-linux-x86_64.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/pyparsing-2.2.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/cycler-0.10.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/subprocess32-3.2.7-py2.7-linux-x86_64.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/functools32-3.2.3.post2-py2.7.egg
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/python_dateutil-2.6.0-py2.7.egg
/dls/science/users/gw56/svn/cctbx/modules/cctbx_project
/dls/science/users/gw56/svn/cctbx/modules
/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/boost_adaptbx
/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/pythonpath
/dls/science/users/gw56/svn/cctbx/build/lib
/dls/science/users/gw56/svn/cctbx/base/lib/site-python
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages
/dls/science/users/gw56/svn/cctbx/base/lib/python27.zip
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/plat-linux2
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/lib-tk
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/lib-old
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/lib-dynload
/home/gw56/.local/lib/python2.7/site-packages
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/PIL
/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/site-packages/wx-3.0-gtk2
```

(this was from xia2)

manually importing in dials works fine, code snippet above which used to show this problem is fine, very much an issue in importing in xia2 land now...

**Comment by graeme-winter** [comment]
ulimit -n 4096 solves this problem; #todo add this automatically to xia2 (will do separately)
