### ISSUE TITLE
Spacegroup H32 not recognised by xia2 (any more?)

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#123]

**Comment by graeme-winter** [comment]
```
-------------------- Preparing DEFAULT ---------------------
Status: error "spacegroup H 3 2 unknown"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

```
[gw56@cs04r-sc-com99-02 4]$ cat xia2.error 
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/command_line/xia2_main.py", line 299, in run
    xinfo = xia2_main()
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/command_line/xia2_main.py", line 246, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/Schema/XProject.py", line 127, in get_output
    result += self._crystals[crystal].get_output()
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/Schema/XCrystal.py", line 474, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/Schema/XCrystal.py", line 867, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/Schema/Interfaces/Scaler.py", line 662, in get_scaled_merged_reflections
    self.scale()
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/Schema/Interfaces/Scaler.py", line 621, in scale
    self._scale_prepare()
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/Modules/Scaler/CCP4ScalerA.py", line 753, in _scale_prepare
    ignore_errors=PhilIndex.params.xia2.settings.small_molecule)
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/Wrappers/CCP4/Pointless.py", line 415, in decide_pointgroup
    'Space group from HKLREF file :', '').strip())
  File "/dls_sw/apps/dials/dials-v1-5-1/modules/xia2/lib/SymmetryLib.py", line 88, in spacegroup_name_xHM_to_old
    raise RuntimeError, 'spacegroup %s unknown' % xHM
RuntimeError: spacegroup H 3 2 unknown
```

Working on reproducing in /dls/tmp/gw56/xia2-123

**Comment by graeme-winter** [comment]
In other news, this code should probably not exist, and even if it does exist it should cache the tables:

```
def spacegroup_name_xHM_to_old(xHM):
  '''Convert to an old name.'''

  # generate mapping table

  mapping = { }
  current_old = ''
  current_xHM = ''

  for line in open(syminfo, 'r').readlines():
    if line[0] == '#':
      continue
```

etc

**Comment by graeme-winter** [comment]
Proposed fix: if name not found in map above but name in target list of old style names, use the name:

```
Graemes-MBP-5:lib graeme$ dials.python SymmetryLib.py 'H 3 2'
H 3 2
```

```
   current_xHM = ''
 
+  old_names = []
+
   for line in open(syminfo, 'r').readlines():
     if line[0] == '#':
       continue
@@ -81,10 +83,13 @@ def spacegroup_name_xHM_to_old(xHM):
 
     if 'end_spacegroup' in line:
       mapping[current_xHM] = current_old
+      old_names.append(current_old)
 
   xHM = xHM.upper()
 
   if not xHM in mapping.keys():
+    if xHM in old_names:
+      return xHM
     raise RuntimeError, 'spacegroup %s unknown' % xHM

```

**Comment by graeme-winter** [comment]
We could probably patch 1.5.1 with this cherry.... @Anthchirp please could you do so since it is Tuesday

**Comment by Anthchirp** [comment]
Cherry picked.

**Comment by rjgildea** [comment]
Shouldn't we just use sgtbx stuff here instead?
