### ISSUE TITLE
"Amplitudes will exceed floating point limit.." error

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#139]
At the end of dataprocessing:
```
(...)
Processing took 00h 03m 12s
Status: error "Amplitudes will exceed floating point limit if converted to intensities (max F = 6.577140e+183)."

Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-6-2/modules/xia2/command_line/xia2_main.py", line 298, in run
    xinfo = xia2_main()
  File "/dls_sw/apps/dials/dials-v1-6-2/modules/xia2/command_line/xia2_main.py", line 269, in xia2_main
    generate_xia2_html(xinfo, filename='xia2.html')
  File "/dls_sw/apps/dials/dials-v1-6-2/modules/xia2/command_line/html.py", line 98, in generate_xia2_html
    xtriage_success, xtriage_warnings, xtriage_danger = report.xtriage_report()
  File "/dls_sw/apps/dials/dials-v1-6-2/modules/xia2/command_line/report.py", line 229, in xtriage_report
    params=xtriage_params,
  File "/dls_sw/apps/dials/dials-v1-6-2/modules/cctbx_project/mmtbx/scaling/xtriage.py", line 732, in __init__
    self.completeness_as_non_anomalous)
  File "/dls_sw/apps/dials/dials-v1-6-2/modules/cctbx_project/mmtbx/scaling/data_statistics.py", line 1000, in __init__
    self.no_aniso_array,0.0,u_star_aniso_removed)
  File "/dls_sw/apps/dials/dials-v1-6-2/modules/cctbx_project/mmtbx/scaling/absolute_scaling.py", line 404, in anisotropic_correction
    "converted to intensities (max F = %e)." % f_max)
OverflowError: Amplitudes will exceed floating point limit if converted to intensities (max F = 6.577140e+183).
```

**Comment by Anthchirp** [comment]
command to reproduce: ```xia2.small_molecule /dls/tmp/wra62962/directories/xia2-139/```

**Comment by Anthchirp** [comment]
From ```absolute_scaling.py```:
>     # XXX check for floating-point overflows (which trigger the Boost trap
>     # and crash the interpreter).  The only known case is 2q8o:IOBS2,SIGIOBS2
>     # which is missing nearly all acentric hkls but it clearly points to a bug
>     # in this routine when dealing with pathological data.

so essentially E_CENTRIC_DATASET_DETECTED.
Trap xtriage failure if small_molecule == True?

**Comment by Anthchirp** [comment]
Waiting for regression tests coming through, then will deploy patch and pick for 1.6.3.
Remainder to be sorted out in #129
