### ISSUE TITLE
Xia2: ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by mevol** [xia2/xia2#142]
XIA2 0.5.336-g46337c3
DIALS 1.dev.1483-gfdb8d79
CCP4 7.0.040

Xia2 seems to finish and produces output files, however xia2.error contains the following message:

[ghp45345@ws071 4JX2]$ cat xia2.error
Traceback (most recent call last):
  File "/dls/science/users/ghp45345/dials/build/../modules/xia2/command_line/xia2_main.py", line 298, in run
    xinfo = xia2_main()
  File "/dls/science/users/ghp45345/dials/build/../modules/xia2/command_line/xia2_main.py", line 269, in xia2_main
    generate_xia2_html(xinfo, filename='xia2.html')
  File "/dls/science/users/ghp45345/dials/modules/xia2/command_line/html.py", line 238, in generate_xia2_html
    html_file = make_logfile_html(logfile)
  File "/dls/science/users/ghp45345/dials/modules/xia2/command_line/html.py", line 288, in make_logfile_html
    tables = extract_loggraph_tables(logfile)
  File "/dls/science/users/ghp45345/dials/modules/xia2/command_line/html.py", line 369, in extract_loggraph_tables
    return data_plots.import_ccp4i_logfile(file_name=logfile)
  File "/dls/science/users/ghp45345/dials/modules/cctbx_project/iotbx/data_plots.py", line 628, in import_ccp4i_logfile
    t.import_loggraph(loggraph)
  File "/dls/science/users/ghp45345/dials/modules/cctbx_project/iotbx/data_plots.py", line 234, in import_loggraph
    self.data[i] = [ x if x is None else int(x) for x in column ]
ValueError: cannot convert float NaN to integer
**************************************************************************************************************
Also some details are then missing in xia2.json

[xia2-debug.txt](https://github.com/xia2/xia2/files/1104681/xia2-debug.txt)
[xia2.txt](https://github.com/xia2/xia2/files/1104684/xia2.txt)

**Comment by Anthchirp** [comment]
minimal test case:

```
$ python
>>> import xia2.command_line.html
>>> xia2.command_line.html.extract_loggraph_tables('/dls/tmp/wra62962/directories/NIShB25e/LogFiles/AUTOMATIC_DEFAULT_WAVE3_truncate.log')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/wra62962/files/dials/modules/xia2/command_line/html.py", line 397, in extract_loggraph_tables
    return data_plots.import_ccp4i_logfile(file_name=logfile)
  File "/scratch/wra62962/files/dials/modules/cctbx_project/iotbx/data_plots.py", line 628, in import_ccp4i_logfile
    t.import_loggraph(loggraph)
  File "/scratch/wra62962/files/dials/modules/cctbx_project/iotbx/data_plots.py", line 234, in import_loggraph
    self.data[i] = [ x if x is None else int(x) for x in column ]
ValueError: cannot convert float NaN to integer
```
