### ISSUE TITLE
Strange reindexing operators from pointless lead to dials.reindex error

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#143]
`$  xia2 pipeline=dials atom=Se /dls/metrix/metrix/anomalous_data/3QNK`

```
$ grep SUMMARY_BEGIN -A 20 /dls/tmp/rjgildea/3QNK/DEFAULT/scale/94_pointless.log
<!--SUMMARY_BEGIN--> $TEXT:Result: $$ $$

Alternative indexing scores relative to reference
       Alternative reindexing        Lklhd      CC     R(E^2)    Number Cell_deviation
 1      [3/2h+1/2k,1/2h-1/2k,-l]     0.344    0.921    0.134    456026      0.16
 2              [k,-h,l]             0.327    0.902    0.142    455445      0.15
 3      [3/2h-1/2k,1/2h+1/2k,l]      0.320    0.899    0.146    455478      0.14
 4              [k,h,-l]             0.003    0.068    0.507    449456      0.15
 5      [3/2h+1/2k,-1/2h+1/2k,l]     0.003    0.067    0.507    449470      0.14
 6     [-3/2h+1/2k,-1/2h-1/2k,l]     0.003    0.064    0.508    449431      0.16


Alternative indexing relative to reference file dials_integrated_reindex.mtz

           Reindex operator            CC      Lklhd  Confidence     File name
  1    [3/2h+1/2k,1/2h-1/2k,-l]      0.921     0.344     0.077    dials_integrated_reindex.mtz


$$ <!--SUMMARY_END-->
# command line:
# pointless  'xmlout' '94_pointless.xml' 'hklref' '/dls/tmp/rjgildea/3QNK/DEFAULT/WAVE1/SWEEP1/integrate/dials_integrated_reindex.mtz' 'hklin' '/dls/tmp/rjgildea/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/dials_integrated_reindex.mtz'
```

```
$ cat /dls/tmp/rjgildea/3QNK/DEFAULT/scale/120_dials.reindex.log 
The following parameters have been modified:

change_of_basis_op = "-3/2*h-1/2*k,-1/2*h+1/2*k,-l"
output {
  experiments = "/dls/tmp/rjgildea/3QNK/DEFAULT/scale/120_experiments_reindexed.json"
  reflections = "/dls/tmp/rjgildea/3QNK/DEFAULT/scale/120_reflections_reindexed.pickle"
}
input {
  experiments = /dls/tmp/rjgildea/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/67_integrated_experiments.json
  reflections = /dls/tmp/rjgildea/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/67_integrated.pickle
}

Traceback (most recent call last):
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/reindex.py", line 243, in <module>
    run(sys.argv[1:])
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/reindex.py", line 197, in run
    cryst_reindexed = cryst_orig.change_basis(change_of_basis_op)
RuntimeError: cctbx Internal Error: /dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/cctbx/sgtbx/rot_mx.cpp(19): Unsuitable value for rational rotation matrix.
# command line:
# dials.reindex  '/dls/tmp/rjgildea/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/67_integrated_experiments.json' 'output.experiments=120_experiments_reindexed.json' '/dls/tmp/rjgildea/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/67_integrated.pickle' 'output.reflections=120_reflections_reindexed.pickle' 'change_of_basis_op=-3/2*h-1/2*k,-1/2*h+1/2*k,-l'
```

**Comment by rjgildea** [comment]
xia2 initially processes in hP setting, then pointless decides it doesn't look like hP so xia2 reprocesses in mC setting. Deposited structure refined in P 31 2 1:
http://www.rcsb.org/pdb/explore.do?structureId=3QNK

**Comment by rjgildea** [comment]
Incorrect, SWEEP1&2 process in hP, SWEEP3 processed in oC:
```
$ grep Autoindexing -A 7 xia2.txt 
------------------- Autoindexing SWEEP1 --------------------
All possible indexing solutions:
hP 146.47 146.47 225.98  90.00  90.00 120.00
oC 146.31 253.68 225.82  90.00  90.00  90.00
mC 253.94 146.45 226.07  90.00  89.98  90.00
mP 146.33 225.85 146.43  90.00 119.96  90.00
aP 146.42 146.53 226.02  89.98  90.00 119.96
Indexing solution:
--
------------------- Autoindexing SWEEP2 --------------------
All possible indexing solutions:
hP 146.52 146.52 226.05  90.00  90.00 120.00
oC 146.40 253.77 225.94  90.00  90.00  90.00
mC 146.57 253.65 226.03  90.00  89.98  90.00
mP 146.37 225.90 146.44  90.00 119.96  90.00
aP 146.53 146.46 226.05  89.99  89.99 119.96
Indexing solution:
--
------------------- Autoindexing SWEEP3 --------------------
All possible indexing solutions:
oC 146.80 255.36 226.62  90.00  90.00  90.00
mC 255.31 146.76 226.57  90.00  89.99  90.00
mP 146.88 226.74 147.29  90.00 119.85  90.00
aP 147.23 146.82 226.65  89.99  89.98  60.15
Indexing solution:
oC 146.80 255.36 226.62  90.00  90.00  90.00
--
```

**Comment by rjgildea** [comment]
dials.refine_bravais_settings_output:
```
-------------------------------------------------------------------------------------------------------------------
Solution Metric fit  rmsd    min/max cc #spots lattice                                 unit_cell  volume      cb_op
-------------------------------------------------------------------------------------------------------------------
      12     0.2394 0.068 -0.069/-0.066  18000      hP 147.39 147.39 227.16  90.00  90.00 120.00 4273755    -a,b,-c
      11     0.2394 0.066 -0.284/-0.086  18000      oC 147.31 254.85 226.88  90.00  90.00  90.00 8517377 a,-a+2*b,c
      10     0.2394 0.065 -0.086/-0.086  18000      mC 254.86 147.31 226.88  90.00  89.97  90.00 8517893  a-2*b,a,c
       9     0.2388 0.066 -0.234/-0.234  18000      mC 147.19 254.67 226.71  90.00  89.99  90.00 8498481 a,-a+2*b,c
       8     0.1804 0.054 -0.284/-0.004  18000      oC 147.88 255.35 227.52  90.00  90.00  90.00 8591267  a-b,a+b,c
       7     0.1804 0.053 -0.277/-0.277  18000      mC 147.80 255.23 227.39  90.00  89.97  90.00 8577507  a-b,a+b,c
       6     0.1796 0.053 -0.004/-0.004  18000      mC 254.91 147.66 227.14  90.00  89.97  90.00 8549181 a+b,-a+b,c
*      5     0.0607 0.035 -0.284/-0.021  18000      oC 146.80 255.36 226.62  90.00  90.00  90.00 8495017 b,-2*a+b,c
*      4     0.0606 0.035 -0.021/-0.021  18000      mC 255.31 146.76 226.57  90.00  89.99  90.00 8489536  2*a-b,b,c
*      3     0.0607 0.035 -0.277/-0.277  18000      mC 146.78 255.34 226.59  90.00  89.99  90.00 8492552 b,-2*a+b,c
*      2     0.0182 0.034 -0.284/-0.284  18000      mP 146.88 226.74 147.29  90.00 119.85  90.00 4254690    -b,-c,a
*      1     0.0000 0.032           -/-  18000      aP 147.23 146.82 226.65  89.99  89.98  60.15 4249300      a,b,c
-------------------------------------------------------------------------------------------------------------------
```

**Comment by rjgildea** [comment]
Not sure where the -ve cc's are coming from, but this appears to be yet another case of spotfinding performing poorly for CCD images (sigh), with lots of "spots" found underneath the beam stop shadow. After setting global_threshold=10 hP solution now happy:
```
$ dials.find_spots datablock.json global_threshold=10
$ dials.index datablock.json strong.pickle
$ dials.refine_bravais_settings experiments.json indexed.pickle
-----------------------------------------------------------------------------------------------------------------
Solution Metric fit  rmsd  min/max cc #spots lattice                                 unit_cell  volume      cb_op
-----------------------------------------------------------------------------------------------------------------
*     12     0.2375 0.067 0.568/0.576  18000      hP 147.40 147.40 227.18  90.00  90.00 120.00 4274776    -a,b,-c
      11     0.2375 0.066 0.194/0.538  18000      oC 147.26 254.77 226.81  90.00  90.00  90.00 8509485 b,-2*a+b,c
*     10     0.2375 0.065 0.538/0.538  18000      mC 254.84 147.29 226.87  90.00  90.03  90.00 8515561  2*a-b,b,c
       9     0.2370 0.066 0.289/0.289  18000      mC 147.16 254.64 226.69  90.00  89.99  90.00 8494782 b,-2*a+b,c
       8     0.1801 0.054 0.192/0.714  18000      oC 147.84 255.29 227.47  90.00  90.00  90.00 8585261  a-b,a+b,c
       7     0.1801 0.053 0.192/0.192  18000      mC 147.75 255.14 227.32  90.00  90.03  90.00 8569319  a-b,a+b,c
*      6     0.1794 0.053 0.714/0.714  18000      mC 254.88 147.63 227.11  90.00  89.97  90.00 8545514 a+b,-a+b,c
*      5     0.0589 0.035 0.194/0.678  18000      oC 146.80 255.37 226.62  90.00  90.00  90.00 8495770 a,-a+2*b,c
*      4     0.0589 0.035 0.678/0.678  18000      mC 255.34 146.79 226.60  90.00  90.01  90.00 8493533  a-2*b,a,c
*      3     0.0588 0.035 0.211/0.211  18000      mC 146.76 255.31 226.57  90.00  89.99  90.00 8489292 a,-a+2*b,c
*      2     0.0171 0.033 0.194/0.194  18000      mP 146.95 226.85 147.36  90.00 119.85  90.00 4260519     -a,c,b
*      1     0.0000 0.033         -/-  18000      aP 146.84 147.24 226.66  89.98  89.99  60.15 4250106      a,b,c
-----------------------------------------------------------------------------------------------------------------
```

**Comment by rjgildea** [comment]
I think the high resolution "indexed" reflections behind the beam stop shadow are probably ultimately to blame for the negative cc's in RBS:
![screenshot-53](https://user-images.githubusercontent.com/2810624/27651459-4cef9194-5c30-11e7-9517-a322f611c0c8.png)

**Comment by graeme-winter** [comment]
OK, case for where we need settings=CCD or something available in xia2 (i.e. phil settings) which would be used automagically for dials jobs; see also https://github.com/dials/dials/issues/23 and https://github.com/dials/dials/issues/371
