### ISSUE TITLE
Latest modifications to LABELIT cause xia2 test failure

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#158]
```
libtbx.python "/Users/graeme/svn/cctbx/modules/xia2/Test/Modules/Indexer/TstLabelitIndexerII.py"
All possible indexing solutions:
cI  78.49  78.49  78.49  90.00  90.00  90.00
Indexing solution:
cI  78.49  78.49  78.49  90.00  90.00  90.00
approx_equal eps: 1e-06
approx_equal multiplier: 10000000000.0
  78.49 approx_equal ERROR
  78.52 approx_equal ERROR

  78.4899892595 approx_equal ERROR
  78.52 approx_equal ERROR

  78.4900171581 approx_equal ERROR
  78.52 approx_equal ERROR

  90.0000026016
  90

  89.9999866727
  90

  89.9999898074
  90

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/modules/xia2/Test/Modules/Indexer/TstLabelitIndexerII.py", line 71, in <module>
    run()
  File "/Users/graeme/svn/cctbx/modules/xia2/Test/Modules/Indexer/TstLabelitIndexerII.py", line 66, in run
    exercise_labelit_indexerii()
  File "/Users/graeme/svn/cctbx/modules/xia2/Test/Modules/Indexer/TstLabelitIndexerII.py", line 46, in exercise_labelit_indexerii
    assert approx_equal(ls.get_indexer_cell(), (78.52, 78.52, 78.52, 90, 90, 90))
AssertionError
```

Possibly due to this commit?

"Default mosaicity target now set to the superior ML target described in 2014.  Not certain why the default has remained LSQ for so long, nevertheless ML is preferable."

**Comment by graeme-winter** [comment]
https://github.com/cctbx/cctbx_project/commit/166904e?

**Comment by rjgildea** [comment]
All this means is that something in Labelit has changed (we know) leading to a slightly different unit cell (which probably doesn't make much difference in the long run). I suggest updating the expected unit cell in the test which will make the test failure go away and make the world a (slightly) happier place.

**Comment by graeme-winter** [comment]
Almost certainly a good idea

Wanted to know why this happened hence ticket

Will make eps 1e-3 => problem solved

**Comment by graeme-winter** [comment]
(and many others)....
