### ISSUE TITLE
H -3

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#16]
```xia2 multi_sweep_indexing=true read_all_image_headers=false trust_beam_centre=true -small_molecule -dials /dls/i19-1/data/2016/mt12745-3/973_CK_collection```

```
-------------------- Preparing DEFAULT ---------------------
Likely spacegroups:
H -3
Reindexing to first spacegroup setting: H -3 (h,k,l)
--------------------- Scaling DEFAULT ----------------------
Resolution limit for NATIVE/SWEEP1:  1.65
Resolution limit for NATIVE/SWEEP2:  1.47
Resolution limit for NATIVE/SWEEP3:  1.35
Resolution limit for NATIVE/SWEEP4:  1.44
--------------------- Scaling DEFAULT ----------------------
Resolution limit for NATIVE/SWEEP1:  1.65
Resolution limit for NATIVE/SWEEP2:  1.47
Resolution limit for NATIVE/SWEEP3:  1.35
Resolution limit for NATIVE/SWEEP4:  1.44

Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/xia2/command_line/xia2_main.py", line 283, in run
    xinfo = xia2_main()
  File "/scratch/wra62962/files/dials/build/../modules/xia2/command_line/xia2_main.py", line 229, in xia2_main
    Chatter.write(xinfo.get_output())
  File "/scratch/wra62962/files/dials/modules/xia2/Schema/XProject.py", line 131, in get_output
    result += self._crystals[crystal].get_output()
  File "/scratch/wra62962/files/dials/modules/xia2/Schema/XCrystal.py", line 464, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/scratch/wra62962/files/dials/modules/xia2/Schema/XCrystal.py", line 903, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/scratch/wra62962/files/dials/modules/xia2/Schema/Interfaces/Scaler.py", line 675, in get_scaled_merged_reflections
    self.scale()
  File "/scratch/wra62962/files/dials/modules/xia2/Schema/Interfaces/Scaler.py", line 639, in scale
    self._scalr_result = self._scale()
  File "/scratch/wra62962/files/dials/modules/xia2/Modules/Scaler/CCP4ScalerA.py", line 1247, in _scale
    self._scalr_scaled_reflection_files['mtz_unmerged'][key])
  File "/scratch/wra62962/files/dials/modules/xia2/Modules/Scaler/CommonScaler.py", line 1076, in _compute_scaler_statistics
    sg = sgtbx.space_group_info(str(self._scalr_likely_spacegroups[0])).group()
  File "/scratch/wra62962/files/dials/modules/cctbx_project/cctbx/sgtbx/__init__.py", line 97, in __init__
    symbols = space_group_symbols(symbol)
RuntimeError: cctbx Error: Space group symbol not recognized: H -3
```

**Comment by rjgildea** [comment]
This should hopefully be fixed by http://sourceforge.net/p/cctbx/code/24320
