### ISSUE TITLE
new XDS; please update settings in xia2 tests

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#173]
e.g.:

```
libtbx.python "/dls/science/users/gw56/svn/cctbx/modules/xia2/Test/Modules/Indexer/TstXDSIndexerII.py" 1 [FAIL]
  Time: 59.99
  Return code: 1
  OKs: 0
  Standard error:
    Traceback (most recent call last):
      File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Test/Modules/Indexer/TstXDSIndexerII.py", line 98, in <module>
        run(sys.argv[1:])
      File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Test/Modules/Indexer/TstXDSIndexerII.py", line 93, in run
        exercise_xds_indexer(nproc=nproc)
      File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Test/Modules/Indexer/TstXDSIndexerII.py", line 56, in exercise_xds_indexer
        eps=1e-2), indexer.get_indexer_cell()
    AssertionError: (78.85312235943768, 78.85313436587822, 78.85313019175184, 90.00000155684344, 90.00000542864572, 90.00000444368627)
```

**Comment by graeme-winter** [comment]
Hmm for this test the unit cell parameters have changed a great deal viz:

```
  78.8531223594 approx_equal ERROR
  78.054 approx_equal ERROR
```

**Comment by graeme-winter** [comment]
N.B. new === BUILT=20170720
