### ISSUE TITLE
NameError: global name 'Pointless' is not defined

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#189]
Occurred twice processing I23 data:

```
[gw56@cs03r-sc-serv-16 001-dials-3]$ cat xia2.error 
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 315, in run
    xinfo = xia2_main()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 251, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/XProject.py", line 126, in get_output
    result += self._crystals[crystal].get_output()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/XCrystal.py", line 468, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/XCrystal.py", line 861, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 646, in get_scaled_merged_reflections
    self.scale()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 617, in scale
    self._scale_prepare()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Modules/Scaler/CCP4ScalerA.py", line 496, in _scale_prepare
    hklin, si.get_integrater().get_phi_width())
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Modules/Scaler/CCP4ScalerA.py", line 1363, in _prepare_pointless_hklin
    hklin, phi_width)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Modules/Scaler/CCP4ScalerHelpers.py", line 211, in _prepare_pointless_hklin
    pl = Pointless()
NameError: global name 'Pointless' is not defined
```

Weird, as obviously this is defined. Assert: pyc compilation error? Anyhow, we should document how to check for weird errors / how to fix.

**Comment by graeme-winter** [comment]
Hmmm clearing .pyc's did not clear this

🤔

**Comment by graeme-winter** [comment]
😱 this is a real bug

**Comment by graeme-winter** [comment]
Also to do:
 - add tests which include > 180 or > 360 degrees of data
