### ISSUE TITLE
xia2 fails on Windows because of "resource"

### ISSUE THREAD

**Issue by dagewa** [xia2/xia2#194]
Charles told me that xia2 fails on Windows because of the use of UNIX-only library resource. Looking through the code I'm guessing that this is the culprit:
https://github.com/xia2/xia2/blob/master/Handlers/Environment.py#L76

the other `import resource` is wrapped in a try block.

**Comment by dagewa** [comment]
Yep, Charles confirms
```
Traceback (most recent call last):
  File "C:\CCP4-7\7.0\lib\py2\site-packages\xia2\command_line\xia2_main.py", line 296, in run
    check_environment()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\xia2\Applications\xia2_main.py", line 52, in check_environment
    v = Environment.getenv(k)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\xia2\Handlers\Environment.py", line 148, in getenv
    self._setup()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\xia2\Handlers\Environment.py", line 112, in _setup
    ulimit = ulimit_n()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\xia2\Handlers\Environment.py", line 77, in ulimit_n
    import resource
ImportError: No module named resource
```

**Comment by Anthchirp** [comment]
The benefits of having Windows builds. On it.

**Comment by rjgildea** [comment]
Looks like @graeme-winter added this ~3 months ago, it only seems to print something to the debug log anyway, so shouldn't cause any problems by putting in a try/except somewhere:
https://github.com/xia2/xia2/commit/c4bbd78c590a5c9f15d4742b1574339041779253

**Comment by graeme-winter** [comment]
Oh, this

try/except should be fine - only useful on UNIX

**Comment by dagewa** [comment]
Ta, passed to Charles to patch the update.
