### ISSUE TITLE
Rigaku RAXIS detectors with 2d pipeline, error

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#200]
User report, just reproduced:

```
Free space:        4542.74 GB
Host: cs04r-sc-com99-05
Contact: xia2.support@gmail.com
XIA2 0.5.484-g850f714
DIALS 1.dev.1892-gd377648
CCP4 7.0.046
Command line: xia2 pipeline=2di /dls/mx-scratch/gw56/drives/1/detectors/image_plate/raxis
------------------- Autoindexing SWEEP1 --------------------
All possible indexing solutions:
tP  77.94  77.94  36.71  90.00  90.00  90.00
oC 109.80 110.62  36.71  90.00  90.00  90.00
oP  36.71  77.87  78.00  90.00  90.00  90.00
mC 109.80 110.62  36.71  90.00  90.10  90.00
mP  77.87  36.71  78.00  90.00  90.40  90.00
aP  36.71  77.87  78.00  90.40  90.10  90.10
Indexing solution:
tP  78.08  78.08  36.74  90.00  90.00  90.00
Status: error "float argument required, not NoneType"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com

```

Will follow up

**Comment by graeme-winter** [comment]
Error:

```
[gw56@cs03r-sc-serv-16 2d]$ cat xia2.error 
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 315, in run
    xinfo = xia2_main()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 232, in xia2_main
    sweep.get_integrater_intensities()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/XSweep.py", line 864, in get_integrater_intensities
    reflections = self._get_integrater().get_integrater_intensities()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Interfaces/Integrater.py", line 600, in get_integrater_intensities
    self.integrate()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Interfaces/Integrater.py", line 538, in integrate
    self._integrate_prepare()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Modules/Integrater/MosflmIntegrater.py", line 90, in _integrate_prepare
    self.get_integrater_epoch())[0]
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Interfaces/Refiner.py", line 246, in get_refined_experiment_list
    self.refine()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Interfaces/Refiner.py", line 220, in refine
    self._refinr_result = self._refine()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Modules/Refiner/MosflmRefiner.py", line 144, in _refine
    idxr, 'aP')
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Modules/Refiner/MosflmRefiner.py", line 382, in _mosflm_test_refine_cell
    refiner.run()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Wrappers/Mosflm/MosflmRefineCell.py", line 166, in run
    self.input('beam %f %f' %self._beam_centre)
TypeError: float argument required, not NoneType
```

**Comment by graeme-winter** [comment]
Suspect that beam_centre is supposed to come from previous run; was not gathered - though was in index output:

```
Initial cell (before refinement) is   77.9305   77.9305   36.7062  90.000  90.000  90.000
Using  772 indexed reflections (out of  821 spots used in indexing, {delta(XY) <= 2.5 sigma}),
final sd in spot positions is 0.25mm and in phi 0.20 degrees
Refined cell parameters   78.08   78.08   36.74  90.00  90.00  90.00
Beam coordinates of 150.01 149.85 have been refined to 150.04 150.62
***** WARNING ***** WARNING ***** WARNING ***** WARNING ***** WARNING ***** WARNING 
This is a shift of  0.77mm or  0.339 times the minimum spot separation of ca  2.27mm.
```

**Comment by graeme-winter** [comment]
Beam centre coming in as (None, None) 🤔

**Comment by graeme-winter** [comment]
I think this relates to the direction of the detector normal...

```
def beam_centre(detector, beam):
  s0 = beam.get_s0()
  x, y = (None, None)
  for panel_id, panel in enumerate(detector):
    try:
      x, y = panel.get_ray_intersection(s0)
    except RuntimeError:
      continue
    else:
      if panel.is_coord_valid_mm((x, y)):
        break
  return panel_id, (x, y)
```

**Comment by graeme-winter** [comment]
```
-      x, y = panel.get_ray_intersection(s0)
+      x, y = panel.get_bidirectional_ray_intersection(s0)
```

=>

```
tP  78.08  78.08  36.74  90.00  90.00  90.00
Status: error "dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/model/detector.h(803): DXTBX_ASSERT(w_max > 0) failure."
```

now i.e. part of the problem is found

**Comment by graeme-winter** [comment]
OK, root cause of the rest is that the distance is negative then gets set positive...

**Comment by graeme-winter** [comment]
Fixed...

```
For AUTOMATIC/DEFAULT/NATIVE                 Overall    Low     High
High resolution limit                           1.52    4.12    1.52
Low resolution limit                           25.51   25.51    1.55
Completeness                                   65.2    71.5     5.3
Multiplicity                                    1.8     2.0     1.0
I/sigma                                        16.0    25.0     3.2
Rmerge(I)                                     0.037   0.038   0.177
Rmerge(I+/-)                                  0.034   0.035   0.000
Rmeas(I)                                      0.048   0.048   0.251
Rmeas(I+/-)                                   0.047   0.047   0.000
Rpim(I)                                       0.031   0.029   0.177
Rpim(I+/-)                                    0.032   0.031   0.000
CC half                                       0.997   0.994   0.000
Wilson B factor                              11.340
Anomalous completeness                         32.8    37.2     0.1
Anomalous multiplicity                          1.2     1.5     1.0
Anomalous correlation                        -0.272  -0.167   0.000
Anomalous slope                               1.048
Total observations                            21268    1476      50
Total unique                                  12054     742      49
Assuming spacegroup: P 41 2 2
Other likely alternatives are:
P 41 21 2
P 43 2 2
P 43 21 2
Unit cell:
 78.826  78.826  36.956
 90.000  90.000  90.000
mtz format:
Scaled reflections: /private/tmp/200/2d/DataFiles/AUTOMATIC_DEFAULT_free.mtz
mtz_unmerged format:
Scaled reflections (NATIVE): /private/tmp/200/2d/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz
sca format:
Scaled reflections (NATIVE): /private/tmp/200/2d/DataFiles/AUTOMATIC_DEFAULT_scaled.sca
sca_unmerged format:
Scaled reflections (NATIVE): /private/tmp/200/2d/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.sca
Processing took 00h 00m 56s
XIA2 used... aimless, ccp4, mosflm, pointless, xia2
Here are the appropriate citations (BIBTeX in xia2-citations.bib.)
Evans, P. (2006) Acta Cryst. D62, 72-82.
Evans, P. R. and Murshudov, G. N. (2013) Acta Cryst. D69, 1204-1214.
Leslie, A. G. W. and Powell, H. R. (2007) Evolving Methods in Macromolecular Crystallography 245, 41-51.
Winn, M. D. et al. (2011) Acta Cryst. D67, 235-242.
Winter, G. (2010) J. Appl. Cryst. 43, 186-190.
Status: normal termination
```

**Comment by graeme-winter** [comment]
Commits in this ticket would be ++ nice for next dials 😄

**Comment by graeme-winter** [comment]
Now does not work for cubic insulin test data (ADSC) => reopen
