### ISSUE TITLE
working directory change

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#214]
This just failed ~~on Mac~~:

```
Environment configuration...
Python => /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/build_dials/build/../base/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
CCTBX => /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/build_dials/modules
CCP4 => /usr/local/ccp4-7.0
CLIBD => /usr/local/ccp4-7.0/lib/data
CCP4_SCR => /var/folders/wb/hpx7xlg15ks1z88z0m5md70m0000gq/T/tmp5f9L46
Starting directory: /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds
Working directory: /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds
Free space:        746.12 GB
Contact: xia2.support@gmail.com
XIA2 0.5.538-g497e8d37
DIALS 1.dev.2083-g33e10b1e
CCP4 7.0.046
Command line: xia2 pipeline=3di nproc=1 njob=2 mode=parallel trust_beam_centre=True /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/build_dials/build/xia2_regression/test_data/mad_example
------------------- Autoindexing SWEEP1 --------------------
All possible indexing solutions:
tP  51.80  51.80 158.20  90.00  90.00  90.00
oC  73.20  73.40 158.20  90.00  90.00  90.00
oP  51.80  51.80 158.20  90.00  90.00  90.00
mC  73.20  73.40 158.20  90.00  90.00  90.00
mP  51.80  51.80 158.20  90.00  90.00  90.00
aP  51.80  51.80 158.20  90.00  90.00  90.10
Indexing solution:
tP  51.80  51.80 158.22  90.00  90.00  90.00
-------------------- Integrating SWEEP1 --------------------
Processed batches 1 to 60
Standard Deviation in pixel range: 0.72 0.75
Integration status per image:
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
"o" => good        "%" => ok        "!" => bad rmsd
"O" => overloaded  "#" => many bad  "." => weak
"@" => abandoned
Maximum relative deviation in cell: 0.001
Mosaic spread: 0.207 < 0.227 < 0.263
-------------------- Integrating SWEEP1 --------------------
Processed batches 1 to 60
Standard Deviation in pixel range: 0.73 0.75
Integration status per image:
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
"o" => good        "%" => ok        "!" => bad rmsd
"O" => overloaded  "#" => many bad  "." => weak
"@" => abandoned
Maximum relative deviation in cell: 0.001
Mosaic spread: 0.188 < 0.188 < 0.188

Loading sweep: SWEEP1
------------------- Autoindexing SWEEP2 --------------------
All possible indexing solutions:
tP  51.85  51.85 158.20  90.00  90.00  90.00
oC  73.20  73.40 158.20  90.00  90.00  90.00
oP  51.80  51.90 158.20  90.00  90.00  90.00
mC  73.20  73.40 158.20  90.00  90.00  90.00
mP  51.80 158.20  51.90  90.00  90.20  90.00
aP  51.80  51.90 158.20  90.00  90.00  90.20
Indexing solution:
tP  51.83  51.83 158.30  90.00  90.00  90.00
-------------------- Integrating SWEEP2 --------------------
Processed batches 1 to 60
Standard Deviation in pixel range: 0.74 0.77
Integration status per image:
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
"o" => good        "%" => ok        "!" => bad rmsd
"O" => overloaded  "#" => many bad  "." => weak
"@" => abandoned
Maximum relative deviation in cell: 0.001
Mosaic spread: 0.213 < 0.236 < 0.256
-------------------- Integrating SWEEP2 --------------------
Processed batches 1 to 60
Standard Deviation in pixel range: 0.74 0.76
Integration status per image:
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
"o" => good        "%" => ok        "!" => bad rmsd
"O" => overloaded  "#" => many bad  "." => weak
"@" => abandoned
Maximum relative deviation in cell: 0.001
Mosaic spread: 0.194 < 0.194 < 0.194

Loading sweep: SWEEP2
-------------------- Preparing DEFAULT ---------------------
--------------------- Scaling DEFAULT ----------------------
Excluding outlier reflections Z > 0.00
--------------------- Scaling DEFAULT ----------------------
Excluding outlier reflections Z > 0.00
--------------------- Scaling DEFAULT ----------------------
Excluding outlier reflections Z > 0.00
--------------------- Scaling DEFAULT ----------------------
Excluding outlier reflections Z > 0.00
--------------------- Scaling DEFAULT ----------------------
Excluding outlier reflections Z > 0.00
--------------------- Scaling DEFAULT ----------------------
Resolution for sweep WAVE1/SWEEP1: 1.58 (cc_half > 0.5, merged <I/sigI> > 1.0)
Resolution for sweep WAVE2/SWEEP2: 1.58 (merged <I/sigI> > 1.0)
--------------------- Scaling DEFAULT ----------------------
Excluding outlier reflections Z > 0.00
--------------------- Scaling DEFAULT ----------------------
Likely spacegroups:
P 41 21 2
P 43 21 2
Reindexing to first spacegroup setting: P 41 21 2 (h,k,l)
Overall twinning score: 2.11
Your data do not appear twinned

------------------ Local Scaling DEFAULT -------------------
WAVE1   0.0 0.00 (ok)
WAVE2   0.0 0.08 (ok)
------------------------------------------------------------
Project: AUTOMATIC
Crystal: DEFAULT
Sequence: 
Wavelength name: WAVE1
Wavelength 0.97966
Sweeps:
SWEEP SWEEP1 [WAVELENGTH WAVE1]
TEMPLATE 12287_1_E1_###.img
DIRECTORY /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/build_dials/build/xia2_regression/test_data/mad_example
IMAGES (USER) 1 to 60
MTZ file: /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE1/SWEEP1/integrate/INTEGRATE_reindex.mtz
Wavelength name: WAVE2
Wavelength 1.00000
Sweeps:
SWEEP SWEEP2 [WAVELENGTH WAVE2]
TEMPLATE 12287_1_E2_###.img
DIRECTORY /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/build_dials/build/xia2_regression/test_data/mad_example
IMAGES (USER) 1 to 60
MTZ file: /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate/INTEGRATE_reindex.mtz
For AUTOMATIC/DEFAULT/WAVE1                  Overall    Low     High
High resolution limit                           1.58    4.29    1.58
Low resolution limit                           35.67   35.68    1.61
Completeness                                   94.0    97.4    63.7
Multiplicity                                    4.1     4.0     2.4
I/sigma                                        16.4    43.2     1.2
Rmerge(I)                                     0.071   0.049   0.761
Rmerge(I+/-)                                  0.039   0.021   0.652
Rmeas(I)                                      0.080   0.056   0.971
Rmeas(I+/-)                                   0.051   0.027   0.918
Rpim(I)                                       0.037   0.026   0.593
Rpim(I+/-)                                    0.031   0.017   0.646
CC half                                       0.998   0.998   0.559
Wilson B factor                              18.513
Anomalous completeness                         89.9    89.7    60.7
Anomalous multiplicity                          2.3     2.5     1.3
Anomalous correlation                         0.820   0.850   0.125
Anomalous slope                               1.621
dF/F                                          0.101
dI/s(dI)                                      1.947
Total observations                           118242    6662    2275
Total unique                                  28675    1665     948
For AUTOMATIC/DEFAULT/WAVE2                  Overall    Low     High
High resolution limit                           1.58    4.29    1.58
Low resolution limit                           43.32   43.33    1.61
Completeness                                   91.8    96.9    57.6
Multiplicity                                    4.0     3.9     2.2
I/sigma                                        17.9    48.3     1.1
Rmerge(I)                                     0.042   0.021   0.751
Rmerge(I+/-)                                  0.036   0.019   0.631
Rmeas(I)                                      0.048   0.025   0.977
Rmeas(I+/-)                                   0.046   0.024   0.892
Rpim(I)                                       0.023   0.012   0.615
Rpim(I+/-)                                    0.029   0.015   0.631
CC half                                       0.999   0.999   0.514
Wilson B factor                              18.374
Anomalous completeness                         86.7    85.1    50.6
Anomalous multiplicity                          2.2     2.5     1.2
Anomalous correlation                        -0.030  -0.032   0.044
Anomalous slope                               0.963
dF/F                                          0.059
dI/s(dI)                                      0.786
Total observations                           112557    6522    1882
Total unique                                  28001    1660     857
Assuming spacegroup: P 41 21 2
Other likely alternatives are:
P 43 21 2
Unit cell:
 51.780  51.780 158.140
 90.000  90.000  90.000
mtz format:
Scaled reflections: /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DataFiles/AUTOMATIC_DEFAULT_free.mtz
mtz_unmerged format:
Scaled reflections (WAVE1): /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE1.mtz
Scaled reflections (WAVE2): /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE2.mtz
sca format:
Scaled reflections (WAVE1): /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DataFiles/AUTOMATIC_DEFAULT_scaled_WAVE1.sca
Scaled reflections (WAVE2): /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DataFiles/AUTOMATIC_DEFAULT_scaled_WAVE2.sca
sca_unmerged format:
Scaled reflections (WAVE1): /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE1.sca
Scaled reflections (WAVE2): /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE2.sca
hkl format:
Processing took 00h 09m 41s
Error: /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate/xia2.txt
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
usr+sys time: 1.09 seconds
wall clock time: 9 minutes 43.41 seconds (583.41 seconds total)
```

xia2.error:
```
Traceback (most recent call last):
  File "/Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/build_dials/build/../modules/xia2/command_line/xia2_main.py", line 315, in run
    xinfo = xia2_main()
  File "/Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/build_dials/build/../modules/xia2/command_line/xia2_main.py", line 279, in xia2_main
    params=params.xia2.settings.report)
  File "/Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/build_dials/modules/xia2/command_line/html.py", line 40, in generate_xia2_html
    assert os.path.isfile(xia2_txt), xia2_txt
AssertionError: /Users/dlshudson/jenkins_slave/workspace/xia2_regression/label/dials-mac-mini/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate/xia2.txt
```

The cwd at that point clearly was inside ```DEFAULT/WAVE2/SWEEP2``` instead of ```.```, which is why the assertion fails. But why though? ~~(And why only on mac?)~~

**Comment by Anthchirp** [comment]
same test just failed on linux, and succeeded on mac. race-condition?

**Comment by Anthchirp** [comment]
Debug trace of a failed xia2 run:
```
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/setup' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/xia2/Applications/xia2setup.py:519
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/xia2/Applications/xia2setup.py:539
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE1/SWEEP1/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:21
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:24
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:21
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE1/SWEEP1/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:21
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:24
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:24
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE1/SWEEP1/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:21
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:24
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE1/SWEEP1/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:21
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:24
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE1/SWEEP1/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:21
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:24
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE1/SWEEP1/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:21
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:24
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE1/SWEEP1/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:21
Directory change to '/scratch/jenkins_slave/workspace/xia2_regression/label/ws168/tests/xia2_regression.mad_example.xds/DEFAULT/WAVE2/SWEEP2/integrate' in /scratch/jenkins_slave/workspace/xia2_regression/label/ws168/build_dials/modules/cctbx_project/dxtbx/serialize/filename.py:24
```

wait, what?!

**Comment by Anthchirp** [comment]
* everything happens within one process (because only main process produces debug output)
* from line 4 we know cwd = main xia2 dir
* line 5, enter context manager 1
* line 6, enter context manager 2
* line 7, leave context manager 1
* line 8, leave context manager 2
* congratulations, cwd is now borked.

=> [tmp_chdir context manager](https://github.com/cctbx/cctbx_project/blob/master/dxtbx/serialize/filename.py#L15) is not thread safe

**Comment by graeme-winter** [comment]
dang :(
