### ISSUE TITLE
Status: error "ctruncate failure"

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#215]
sometimes running xia2 gives eg.

```
------------------- Unit cell refinement -------------------
SAD:  $number $number $number $number $number $number 
Error: ctruncate failure
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```
with

```python
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/xia2/command_line/xia2_main.py", line 332, in run
    xinfo = xia2_main()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/xia2/command_line/xia2_main.py", line 250, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/xia2/Schema/XProject.py", line 126, in get_output
    result += self._crystals[crystal].get_output()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/xia2/Schema/XCrystal.py", line 468, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/xia2/Schema/XCrystal.py", line 861, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/xia2/Schema/Interfaces/Scaler.py", line 642, in get_scaled_merged_reflections
    self.scale()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/xia2/Schema/Interfaces/Scaler.py", line 621, in scale
    self._scale_finish()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/xia2/Modules/Scaler/CommonScaler.py", line 503, in _scale_finish
    self._scale_finish_chunk_3_truncate()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/xia2/Modules/Scaler/CommonScaler.py", line 620, in _scale_finish_chunk_3_truncate
    truncate.truncate()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/xia2/Wrappers/CCP4/Ctruncate.py", line 109, in truncate
    raise RuntimeError('ctruncate failure')
RuntimeError: ctruncate failure
```

Should be more robust against that.

**Comment by rjgildea** [comment]
Is this repeatable? Do you have a specific example?
Does setting `truncate.program=cctbx` fix it?
