### ISSUE TITLE
Running xia2 pipeline=dials-full _twice_ fails the second time

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#247]
First time runs fine, second time

```
xia2 pipeline=dials-full /Users/graeme/svn/cctbx/build/xia2_regression/test_data/X4_wide/
```

gives

```
-------------------- Preparing DEFAULT ---------------------
Likely pointgroup determined by dials.symmetry:
P 4 2 2
--------------------- Scaling DEFAULT ----------------------
Error:
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
Grey-Area:dials graeme$ cat xia2.error 
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 333, in run
    xinfo = xia2_main()
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 251, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XProject.py", line 123, in get_output
    result += self._crystals[crystal].get_output()
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XCrystal.py", line 468, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XCrystal.py", line 859, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 640, in get_scaled_merged_reflections
    self.scale()
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 616, in scale
    self._scalr_result = self._scale()
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/Scaler/DialsScaler.py", line 665, in _scale
    sc.scale()
  File "/Users/graeme/svn/cctbx/modules/xia2/Wrappers/Dials/Scale.py", line 225, in scale
    assert len(self._experiments_json)
AssertionError
```

in same folder => should work...

**Comment by graeme-winter** [comment]
Suspect something lost in translation along the way - not a blocker, but for info would be nice to get this fixed up sometime.
