### ISSUE TITLE
xia2 multi-crystal analysis broken?

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#25]
We probably don't have a test case for this...

<pre>
Graemes-MBP-4:dials2 graeme$ xia2.multi_crystal_analysis 
Environment configuration...
Python => /Users/graeme/svn/cctbx/build/../base/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
CCTBX => /Users/graeme/svn/cctbx/modules
CCP4 => /Applications/ccp4-7.0
CLIBD => /Applications/ccp4-7.0/lib/data
CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpAcBjHP
Working directory: /Users/graeme/Projects/SBGrid/local/5/all/dials2
Free space:        13.97 GB
Contact: xia2.support@gmail.com
XIA2 0.4.0.365-gc614947
Status: error "cell must be a 6-tuple of floats"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
</pre>

Error log:

<pre>
Graemes-MBP-4:dials2 graeme$ cat xia2.error 
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/multi_crystal_analysis.py", line 333, in run
    multi_crystal_analysis()
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/multi_crystal_analysis.py", line 50, in multi_crystal_analysis
    scaler = crystal._get_scaler()
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XCrystal.py", line 977, in _get_scaler
    integraters = self._get_integraters()
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XCrystal.py", line 811, in _get_integraters
    for i in self._wavelengths[wave]._get_integraters():
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XWavelength.py", line 266, in _get_integraters
    integraters.append(s._get_integrater())
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XSweep.py", line 788, in _get_integrater
    self._integrater.set_integrater_refiner(self._get_refiner())
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XSweep.py", line 745, in _get_refiner
    self.get_epoch(self._frames_to_process[0]), self._get_indexer())
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XSweep.py", line 669, in _get_indexer
    self._indexer.set_indexer_input_cell(self._user_cell)
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/Interfaces/Indexer.py", line 595, in set_indexer_input_cell
    raise RuntimeError, 'cell must be a 6-tuple of floats'
RuntimeError: cell must be a 6-tuple of floats
</pre>

**Comment by graeme-winter** [comment]
OK, type is list not tuple it seems...
