### ISSUE TITLE
Space / % in directory breaks xia2

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#258]
```
Silver-Surfer:run graeme$ xia2 /tmp/space-percent/25%\ DMSO
Environment configuration...
Python => /Users/graeme/svn/cctbx/build/../base/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
CCTBX => /Users/graeme/svn/cctbx/modules
CCP4 => /Applications/ccp4-7.0
CLIBD => /Applications/ccp4-7.0/lib/data
CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpOzs11L
Starting directory: /private/tmp/space-percent/run
Working directory: /private/tmp/space-percent/run
Free space:        68.75 GB
Contact: xia2.support@gmail.com
XIA2 0.5.724-g93a8a44c
DIALS 1.dev.2879-gaecbc7b30
CCP4 7.0.048
Command line: xia2 "/tmp/space-percent/25% DMSO"
Error: no sweeps found
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

**Comment by graeme-winter** [comment]
Underlying cause:

```
Traceback (most recent call last):
File "/Users/graeme/svn/cctbx/modules/xia2/Applications/xia2setup_helpers.py", line 15, in get_sweep
sweeplist = SweepFactory(template, directory)
File "/Users/graeme/svn/cctbx/modules/xia2/Schema/Sweep.py", line 33, in SweepFactory
reversephi=PhilIndex.params.xia2.settings.input.reverse_phi)
File "/Users/graeme/svn/cctbx/modules/xia2/Schema/__init__.py", line 115, in load_imagesets
format_kwargs=format_kwargs)
File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 935, in from_filenames
format_kwargs=format_kwargs)
File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 479, in __init__
format_kwargs=format_kwargs)
File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 602, in _create_multi_file_imageset
format_kwargs=format_kwargs)
File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 576, in make_sweep
filenames = [template_format % index for index in indices]
ValueError: unsupported format character 'D' (0x44) at index 23
```
