### ISSUE TITLE
xia2.multiplex / proteinase_k broken

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#289]
```python
    def test_proteinase_k(regression_test, ccp4, dials_data, run_in_tmpdir):
        data_dir = dials_data("multi_crystal_proteinase_k")
        expts = sorted(f.strpath for f in data_dir.listdir("experiments*.json"))
        refls = sorted(f.strpath for f in data_dir.listdir("reflections*.pickle"))
        command_line = ["xia2.multiplex"] + expts + refls
        print(" ".join(command_line))
        result = procrunner.run(command_line)
>       assert not result["exitcode"]
E       assert not 1

../../../../build_dials/modules/xia2/Test/regression/test_multiplex.py:19: AssertionError
```

because of
```

Selecting 8561 reflections with d > 2.47
Using 2 dimensions for analysis
Principal component analysis:
Explained variance: 0.079, 0.0088
Explained variance ratio: 0.9, 0.1
Traceback (most recent call last):
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/build/../modules/xia2/command_line/multiplex.py", line 128, in <module>
    run()
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/build/../modules/xia2/command_line/multiplex.py", line 124, in run
    scaled = ScaleAndMerge.MultiCrystalScale(experiments, reflections_all, params)
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/modules/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 409, in __init__
    self.report()
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/modules/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 604, in report
    mca.report()
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/modules/xia2/command_line/multi_crystal_analysis.py", line 331, in report
    self._cluster_analysis = self.cluster_analysis()
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/modules/xia2/command_line/multi_crystal_analysis.py", line 189, in cluster_analysis
    mca = multi_crystal_analysis(intensities, labels=labels, prefix=None)
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/modules/xia2/Modules/MultiCrystal/__init__.py", line 174, in __init__
    self.compute_correlation_coefficient_matrix()
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/modules/xia2/Modules/MultiCrystal/__init__.py", line 345, in compute_correlation_coefficient_matrix
    dist_mat
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/base/lib/python2.7/site-packages/scipy/spatial/distance.py", line 2174, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/scratch/jenkins_agent/workspace/xia2_regression/label/vm-rhel6w-1/build_dials/base/lib/python2.7/site-packages/scipy/spatial/distance.py", line 2250, in is_valid_dm
    'symmetric.') % name)
ValueError: Distance matrix 'X' must be symmetric.
```

**Comment by graeme-winter** [comment]
Been seen and reported a couple times - though not always happens - library version dependent?

**Comment by Anthchirp** [comment]
It happens consistently on Jenkins (RHEL6) and on my machine (RHEL7), too.

Bisecting based on commit range information from Jenkins says https://github.com/dials/dials/commit/f01e5c938a4e7418bc5dd8d68199b60b5fac2927 to blame.

Reverting this commit makes test go green.

**Comment by rjgildea** [comment]
This looks to be just floating point difference causing an exact test on symmetry of the distance matrix to fail:
```
for e in range(1,17):
    tol = 10**-e
    print("%e" % tol, ssd.is_valid_dm(dist_mat, tol=tol, throw=False))
    ssd.is_valid_dm(dist_mat, tol=tol)
print(0.0, ssd.is_valid_dm(dist_mat, tol=0.0, throw=False))
```

```
1.000000e-01 True
1.000000e-02 True
1.000000e-03 True
1.000000e-04 True
1.000000e-05 True
1.000000e-06 True
1.000000e-07 True
1.000000e-08 True
1.000000e-09 True
1.000000e-10 True
1.000000e-11 True
1.000000e-12 True
1.000000e-13 True
1.000000e-14 True
1.000000e-15 True
1.000000e-16 False
0.0 False
```
