### ISSUE TITLE
no spotfinding histogram on empty sweeps

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#29]
"Data" collected after shutdown, should give an indication as to what happened in sweep 4

``` cat /dls/i19-1/data/2016/mt11231-9/processed/MJR1901/3Al/4/xia2.txt ```

**Comment by graeme-winter** [comment]
```
-------------------- Spotfinding SWEEP4 --------------------


Status: error "dials.detect_blanks terminated with an error: see /dls/tmp/gw56/29/DEFAULT/NATIVE/SWEEP1/index/8_dials.detect_blanks.log for more details"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

```

Analysis of 0 strong reflections:
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/detect_blanks.py", line 295, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/detect_blanks.py", line 234, in run
    fractional_loss=params.counts_fractional_loss)
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/detect_blanks.py", line 50, in blank_counts_analysis
    assert phi_min <= flex.min(phi)
RuntimeError: min() argument is an empty array
# command line:
# dials.detect_blanks  '7_SWEEP4_datablock.json' '7_SWEEP4_strong.pickle' 'json=8_blanks.json'
```

**Comment by graeme-winter** [comment]
If len(input_spots) == 0 should flag all images as blank somehow; xia2 should fail saying all images blank unless remove blank in which case sweep should be discarded. Started to look at this, should be easy enough.

**Comment by Anthchirp** [comment]
Now crashes out with useful message.
```
$ xia2 multi_sweep_indexing=true read_all_image_headers=false trust_beam_centre=true -small_molecule -dials image=/dls/i19-1/data/2016/mt11231-9/MJR1901/3Al/C1_01_00001.cbf image=/dls/i19-1/data/2016/mt11231-9/MJR1901/3Al/C1_02_00001.cbf image=/dls/i19-1/data/2016/mt11231-9/MJR1901/3Al/C1_03_00001.cbf image=/dls/i19-1/data/2016/mt11231-9/MJR1901/3Al/C1_04_00001.cbf
Environment configuration...
Python => /scratch/wra62962/files/dials/build/../base/bin/python2.7
CCTBX => /scratch/wra62962/files/dials/modules
CCP4 => /dls/science/users/wra62962/ccp4/ccp4-7.0
CLIBD => /dls/science/users/wra62962/ccp4/ccp4-7.0/lib/data
CCP4_SCR => /tmp/tmp2rXbI7
Starting directory: /dls/tmp/wra62962/directories/sbj7ENl0
Working directory: /dls/tmp/wra62962/directories/sbj7ENl0
Free space:        4635.17 GB
Host: ws154
Contact: xia2.support@gmail.com
XIA2 0.5.111-gcc9b836
DIALS 1.dev.859-g292bf5d
***
Command line option -dials is deprecated.
Please use pipeline=dials instead
***
***
Command line option -small_molecule is deprecated.
Please use small_molecule=true instead
***
Command line: xia2 multi_sweep_indexing=true read_all_image_headers=false trust_beam_centre=true -small_molecule -dials image=/dls/i19-1/data/2016/mt11231-9/MJR1901/3Al/C1_01_00001.cbf image=/dls/i19-1/data/2016/mt11231-9/MJR1901/3Al/C1_02_00001.cbf image=/dls/i19-1/data/2016/mt11231-9/MJR1901/3Al/C1_03_00001.cbf image=/dls/i19-1/data/2016/mt11231-9/MJR1901/3Al/C1_04_00001.cbf
-------------------- Spotfinding SWEEP1 --------------------
28434 spots found on 900 images (max 546 / bin)
* *  ** * **   **** **                                     *
*************************       *               *  ** *   **
********************************************* **************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                          900
-------------------- Spotfinding SWEEP2 --------------------
17271 spots found on 850 images (max 372 / bin)
                                                           *
***  *  *                              *          *       **
**** ***** *   ***** **  *             * * *****************
****************************** ** **************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                          850
-------------------- Spotfinding SWEEP3 --------------------
16114 spots found on 850 images (max 364 / bin)
                          *                                 
  *  *                    *                             * * 
* *******   * **          *   *          ***    * * ********
**************** ** ** ** ******** ** **********************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                          850
-------------------- Spotfinding SWEEP4 --------------------
Status: error "No spots found in sweep SWEEP4"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```
