### ISSUE TITLE
crystal=foo.001 results in missing .sca file in dials-aimless pipeline

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#307]
```
$ xia2 pipeline=dials-aimless image=/dls/science/groups/scisoft/DIALS/dials_data/x4wide/X4_wide_M1S4_2_0001.cbf:1:20 crystal=foo.001
...
--------------------- Scaling foo.001 ----------------------
Resolution for sweep NATIVE/SWEEP1: 1.24 (merged <I/sigI> > 1.0)
--------------------- Scaling foo.001 ----------------------
------------------- Unit cell refinement -------------------
NATIVE:  42.43  42.43  39.78  90.00  90.00  90.00
Error: Required file /dls/tmp/rjgildea/tst/001/foo.001/scale/AUTOMATIC_foo.001_scaled.sca not found
```
```
$ cat xia2.error 
Traceback (most recent call last):
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 372, in run
    xia2_main()
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 282, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/xia2/Schema/XProject.py", line 131, in get_output
    result += self._crystals[crystal].get_output()
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/xia2/Schema/XCrystal.py", line 507, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/xia2/Schema/XCrystal.py", line 956, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 668, in get_scaled_merged_reflections
    self.scale()
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 644, in scale
    self._scalr_result = self._scale()
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/xia2/Modules/Scaler/CCP4ScalerA.py", line 1250, in _scale
    FileHandler.record_data_file(scaout)
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/xia2/Handlers/Files.py", line 180, in record_data_file
    assert os.path.isfile(filename), "Required file %s not found" % filename
AssertionError: Required file /dls/tmp/rjgildea/tst/001/foo.001/scale/AUTOMATIC_foo.001_scaled.sca not found
```

**Comment by graeme-winter** [comment]
There are lots of constraints on what crystal etc can be called

We should enforce those up front

Letters, numbers, underscore only and first character not digit
