### ISSUE TITLE
Issues processing MAD data with scaler=ccp4a

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#314]
Filename registration != right - 

```
cs03r-sc-serv-16 scale :) $ cat ../../*error
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/xia2_main.py", line 372, in run
    xia2_main()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/xia2_main.py", line 319, in xia2_main
    cleanup()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Handlers/Files.py", line 210, in cleanup
    FileHandler.cleanup()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Handlers/Files.py", line 143, in cleanup
    shutil.copyfile(f, filename)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/dls/tmp/gw56/mad/mad-ccp4a/DEFAULT/scale/AUTOMATIC_DEFAULT_merged.mtz'
```

```
cs03r-sc-serv-16 scale :) $ ls *mtz
AUTOMATIC_DEFAULT_chef_unmerged.mtz
AUTOMATIC_DEFAULT_chef_WAVE1.mtz
AUTOMATIC_DEFAULT_chef_WAVE2.mtz
AUTOMATIC_DEFAULT_prepointless_sorted.mtz
AUTOMATIC_DEFAULT_scaled_test_unmerged.mtz
AUTOMATIC_DEFAULT_scaled_unmerged_WAVE1.mtz
AUTOMATIC_DEFAULT_scaled_unmerged_WAVE2.mtz
AUTOMATIC_DEFAULT_scaled_WAVE1.mtz
AUTOMATIC_DEFAULT_scaled_WAVE2.mtz
AUTOMATIC_DEFAULT_sorted.mtz
AUTOMATIC_DEFAULT_WAVE1_SWEEP1_integrated.mtz
AUTOMATIC_DEFAULT_WAVE2_SWEEP2_integrated.mtz
pointless.mtz
```

**Comment by graeme-winter** [comment]
Working on this now

**Comment by graeme-winter** [comment]
Weirdly with actual MAD data it works fine?

```
MTZ file: /Users/graeme/issues/314/DEFAULT/WAVE2/SWEEP2/integrate/dials_integrated.mtz
For AUTOMATIC/DEFAULT/WAVE1                  Overall    Low     High
High resolution limit                           1.57    4.26    1.57
Low resolution limit                           36.74   36.75    1.60
Completeness                                   93.7    99.9    61.2
Multiplicity                                    4.1     4.0     2.3
I/sigma                                        11.9    28.7     1.1
Rmerge(I)                                     0.080   0.055   0.717
Rmerge(I+/-)                                  0.049   0.028   0.583
Rmeas(I)                                      0.091   0.062   0.925
Rmeas(I+/-)                                   0.063   0.036   0.825
Rpim(I)                                       0.042   0.029   0.575
Rpim(I+/-)                                    0.039   0.022   0.583
CC half                                       0.997   0.997   0.718
Wilson B factor                              16.450
Anomalous completeness                         92.0    98.8    56.5
Anomalous multiplicity                          2.2     2.4     1.3
Anomalous correlation                         0.715   0.801   0.174
Anomalous slope                               1.390
dF/F                                          0.107
dI/s(dI)                                      1.506
Total observations                           117292    6859    2083
Total unique                                  28663    1717     913
For AUTOMATIC/DEFAULT/WAVE2                  Overall    Low     High
High resolution limit                           1.56    4.23    1.56
Low resolution limit                           36.75   36.76    1.59
Completeness                                   88.4   100.0    28.5
Multiplicity                                    4.0     4.0     1.3
I/sigma                                        12.6    29.1     0.5
Rmerge(I)                                     0.052   0.030   0.992
Rmerge(I+/-)                                  0.047   0.028   0.629
Rmeas(I)                                      0.060   0.035   1.392
Rmeas(I+/-)                                   0.061   0.036   0.889
Rpim(I)                                       0.028   0.017   0.974
Rpim(I+/-)                                    0.038   0.022   0.629
CC half                                       0.999   0.999   0.538
Wilson B factor                              16.645
Anomalous completeness                         83.1    99.1     8.9
Anomalous multiplicity                          2.2     2.5     1.0
Anomalous correlation                        -0.255  -0.198   0.000
Anomalous slope                               0.803
dF/F                                          0.057
dI/s(dI)                                      0.650
Total observations                           110009    7032     569
Total unique                                  27530    1757     429
Assuming spacegroup: P 41 21 2
Other likely alternatives are:
P 43 21 2
Unit cell (with estimated std devs):
51.4840(2) 51.4840(2) 157.3753(7)
90.0       90.0        90.0      
mtz format:
Scaled reflections: /Users/graeme/issues/314/DataFiles/AUTOMATIC_DEFAULT_free.mtz
mtz_unmerged format:
Scaled reflections (WAVE1): /Users/graeme/issues/314/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE1.mtz
Scaled reflections (WAVE2): /Users/graeme/issues/314/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE2.mtz
sca format:
Scaled reflections (WAVE1): /Users/graeme/issues/314/DataFiles/AUTOMATIC_DEFAULT_scaled_WAVE1.sca
Scaled reflections (WAVE2): /Users/graeme/issues/314/DataFiles/AUTOMATIC_DEFAULT_scaled_WAVE2.sca
sca_unmerged format:
Scaled reflections (WAVE1): /Users/graeme/issues/314/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE1.sca
Scaled reflections (WAVE2): /Users/graeme/issues/314/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE2.sca
Processing took 00h 07m 34s
XIA2 used... aimless, ccp4, dials, pointless, xia2
Here are the appropriate citations (BIBTeX in xia2-citations.bib.)
Evans, P. (2006) Acta Cryst. D62, 72-82.
Evans, P. R. and Murshudov, G. N. (2013) Acta Cryst. D69, 1204-1214.
Winn, M. D. et al. (2011) Acta Cryst. D67, 235-242.
Winter, G. (2010) J. Appl. Cryst. 43, 186-190.
Winter, G. et al. (2018) Acta Cryst. D74, 85-97.
Status: normal termination
```

from

`xia2 scaler=ccp4a  /Volumes/Black/Data/jcsg-1vpj-12287-subset`

**Comment by graeme-winter** [comment]
Looks like only an issue if (small molecules) - makes more sense
