### ISSUE TITLE
dials.cosym in multiplex failure

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#315]
```
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/multiplex.py", line 133, in <module>
    run()
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/multiplex.py", line 129, in run
    scaled = ScaleAndMerge.MultiCrystalScale(experiments, reflections_all, params)
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 397, in __init__
    self.report()
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 593, in report
    mca.report()
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/MultiCrystalAnalysis.py", line 189, in report
    self._cluster_analysis = self.cluster_analysis()
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/MultiCrystalAnalysis.py", line 138, in cluster_analysis
    mca = multi_crystal_analysis(intensities, labels=labels, prefix=None)
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/MultiCrystal/__init__.py", line 172, in __init__
    self.run_cosym()
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/MultiCrystal/__init__.py", line 326, in run_cosym
    self.cosym.run()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/symmetry/cosym/__init__.py", line 258, in run
    self._cluster_analysis()
  File "/Users/graeme/svn/cctbx/modules/dials/util/observer.py", line 45, in notify
    r = method(self, *args, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/symmetry/cosym/__init__.py", line 409, in _cluster_analysis
    self.target._lattice_group, space_groups[dataset_id]
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/cctbx/sgtbx/cosets.py", line 49, in __init__
    raise RuntimeError("h is not a subgroup of g")
RuntimeError: h is not a subgroup of g
```

which is _true_ because g, h are:

```
P 4 2 2
P 4 2 2 (c,a,b)
```

Br-soaked lysozyme - suspect that this is because the P1 indexing is different to the P422 one - and data were processed in P4.

**Comment by rjgildea** [comment]
Do you have the input files?

**Comment by graeme-winter** [comment]
Clearly yes, am making available to you now

Here you go

```
Grey-Area multiplex :) $ scp input-for-315.zip gw56@nx-staff:/dls/tmp
input-for-315.zip                             100%  257MB  11.7MB/s   00:22  
```

```
../DEFAULT/SAD/SWEEP1/integrate/10_integrated_experiments.json ../DEFAULT/SAD/SWEEP10/integrate/118_integrated_experiments.json ../DEFAULT/SAD/SWEEP11/integrate/130_integrated_experiments.json ../DEFAULT/SAD/SWEEP12/integrate/142_integrated_experiments.json ../DEFAULT/SAD/SWEEP13/integrate/154_integrated_experiments.json ../DEFAULT/SAD/SWEEP14/integrate/166_integrated_experiments.json ../DEFAULT/SAD/SWEEP15/integrate/178_integrated_experiments.json ../DEFAULT/SAD/SWEEP16/integrate/190_integrated_experiments.json ../DEFAULT/SAD/SWEEP17/integrate/202_integrated_experiments.json ../DEFAULT/SAD/SWEEP18/integrate/214_integrated_experiments.json ../DEFAULT/SAD/SWEEP19/integrate/226_integrated_experiments.json ../DEFAULT/SAD/SWEEP2/integrate/22_integrated_experiments.json ../DEFAULT/SAD/SWEEP20/integrate/238_integrated_experiments.json ../DEFAULT/SAD/SWEEP21/integrate/250_integrated_experiments.json ../DEFAULT/SAD/SWEEP22/integrate/262_integrated_experiments.json ../DEFAULT/SAD/SWEEP23/integrate/274_integrated_experiments.json ../DEFAULT/SAD/SWEEP24/integrate/286_integrated_experiments.json ../DEFAULT/SAD/SWEEP25/integrate/298_integrated_experiments.json ../DEFAULT/SAD/SWEEP26/integrate/310_integrated_experiments.json ../DEFAULT/SAD/SWEEP27/integrate/322_integrated_experiments.json ../DEFAULT/SAD/SWEEP28/integrate/334_integrated_experiments.json ../DEFAULT/SAD/SWEEP29/integrate/346_integrated_experiments.json ../DEFAULT/SAD/SWEEP3/integrate/34_integrated_experiments.json ../DEFAULT/SAD/SWEEP30/integrate/358_integrated_experiments.json ../DEFAULT/SAD/SWEEP31/integrate/370_integrated_experiments.json ../DEFAULT/SAD/SWEEP4/integrate/46_integrated_experiments.json ../DEFAULT/SAD/SWEEP5/integrate/58_integrated_experiments.json ../DEFAULT/SAD/SWEEP6/integrate/70_integrated_experiments.json ../DEFAULT/SAD/SWEEP7/integrate/82_integrated_experiments.json ../DEFAULT/SAD/SWEEP8/integrate/94_integrated_experiments.json ../DEFAULT/SAD/SWEEP9/integrate/106_integrated_experiments.json ../DEFAULT/SAD/SWEEP1/integrate/10_integrated.pickle ../DEFAULT/SAD/SWEEP10/integrate/118_integrated.pickle ../DEFAULT/SAD/SWEEP11/integrate/130_integrated.pickle ../DEFAULT/SAD/SWEEP12/integrate/142_integrated.pickle ../DEFAULT/SAD/SWEEP13/integrate/154_integrated.pickle ../DEFAULT/SAD/SWEEP14/integrate/166_integrated.pickle ../DEFAULT/SAD/SWEEP15/integrate/178_integrated.pickle ../DEFAULT/SAD/SWEEP16/integrate/190_integrated.pickle ../DEFAULT/SAD/SWEEP17/integrate/202_integrated.pickle ../DEFAULT/SAD/SWEEP18/integrate/214_integrated.pickle ../DEFAULT/SAD/SWEEP19/integrate/226_integrated.pickle ../DEFAULT/SAD/SWEEP2/integrate/22_integrated.pickle ../DEFAULT/SAD/SWEEP20/integrate/238_integrated.pickle ../DEFAULT/SAD/SWEEP21/integrate/250_integrated.pickle ../DEFAULT/SAD/SWEEP22/integrate/262_integrated.pickle ../DEFAULT/SAD/SWEEP23/integrate/274_integrated.pickle ../DEFAULT/SAD/SWEEP24/integrate/286_integrated.pickle ../DEFAULT/SAD/SWEEP25/integrate/298_integrated.pickle ../DEFAULT/SAD/SWEEP26/integrate/310_integrated.pickle ../DEFAULT/SAD/SWEEP27/integrate/322_integrated.pickle ../DEFAULT/SAD/SWEEP28/integrate/334_integrated.pickle ../DEFAULT/SAD/SWEEP29/integrate/346_integrated.pickle ../DEFAULT/SAD/SWEEP3/integrate/34_integrated.pickle ../DEFAULT/SAD/SWEEP30/integrate/358_integrated.pickle ../DEFAULT/SAD/SWEEP31/integrate/370_integrated.pickle ../DEFAULT/SAD/SWEEP4/integrate/46_integrated.pickle ../DEFAULT/SAD/SWEEP5/integrate/58_integrated.pickle ../DEFAULT/SAD/SWEEP6/integrate/70_integrated.pickle ../DEFAULT/SAD/SWEEP7/integrate/82_integrated.pickle ../DEFAULT/SAD/SWEEP8/integrate/94_integrated.pickle ../DEFAULT/SAD/SWEEP9/integrate/106_integrated.pickle
```

**Comment by graeme-winter** [comment]
Can reproduce problem with processing in P1, so looks like it does not like lysozyme 🙄

**Comment by graeme-winter** [comment]
Fix verified! Thank you
