### ISSUE TITLE
xia2 appears to hang when starting

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#316]
Possibly as a side-effect of merging https://github.com/xia2/xia2/pull/310 - seems to hang when starting on the reading images / set up phase

**Comment by graeme-winter** [comment]
Stack trace when Ctrl-C

```
Environment configuration...
Python => /Users/graeme/svn/cctbx/build/../base/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
CCTBX => /Users/graeme/svn/cctbx/modules
CCP4 => /Applications/ccp4-7.0
CLIBD => /Applications/ccp4-7.0/lib/data
CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpRXvZL9
Starting directory: /Users/graeme/issues/xia2-316
Working directory: /Users/graeme/issues/xia2-316
Free space:        45.47 GB
Host: Grey-Area
Contact: xia2.support@gmail.com
XIA2 0.6.152-g1d6ce8f4
DIALS 2.dev.537-gfda31cc6d
CCP4 7.0.075
Command line: xia2 /Users/graeme/data/i04_bag_training/
^CTraceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 394, in <module>
    run()
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 372, in run
    xia2_main()
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 54, in xia2_main
    CommandLine = get_command_line()
  File "/Users/graeme/svn/cctbx/modules/xia2/Applications/xia2_main.py", line 113, in get_command_line
    write_xinfo(xinfo, directories)
  File "/Users/graeme/svn/cctbx/modules/xia2/Applications/xia2setup.py", line 628, in write_xinfo
    rummage(directories)
  File "/Users/graeme/svn/cctbx/modules/xia2/Applications/xia2setup.py", line 590, in rummage
    get_sweeps(templates)
  File "/Users/graeme/svn/cctbx/modules/xia2/Applications/xia2setup.py", line 557, in get_sweeps
    preserve_exception_message=True,
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/easy_mp.py", line 627, in parallel_map
    for ( calc, res ) in pfi:
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/forward_compatibility.py", line 23, in next
    return type(self).__next__(self)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/scheduling/parallel_for.py", line 246, in __next__
    self.process_next_one()
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/scheduling/parallel_for.py", line 271, in process_next_one
    ( identifier, result ) = next(self.manager.results()) # raise StopIteration
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/scheduling/job_scheduler.py", line 134, in results
    self.poll()
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/scheduling/job_scheduler.py", line 200, in poll
    ( jobid, res ) = self.inqueue.get( timeout = self.waittime )
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 131, in get
    if not self._poll(timeout):
KeyboardInterrupt
```

**Comment by graeme-winter** [comment]
Anecdotal evidence from @benjaminhwilliams is that this does not affect Ubuntu but is an issue on RHEL and macOS builds.

**Comment by graeme-winter** [comment]
Kudos to @Anthchirp for `nproc=1` suggestion:

```
Grey-Area xia2-316-1 :) $ xia2 nproc=1 ~/data/i04_bag_training/
Environment configuration...
Python => /Users/graeme/svn/cctbx/build/../base/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
CCTBX => /Users/graeme/svn/cctbx/modules
CCP4 => /Applications/ccp4-7.0
CLIBD => /Applications/ccp4-7.0/lib/data
CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmp8SQY9b
Starting directory: /Users/graeme/issues/xia2-316-1
Working directory: /Users/graeme/issues/xia2-316-1
Free space:        45.46 GB
Host: Grey-Area
Contact: xia2.support@gmail.com
XIA2 0.6.152-g1d6ce8f4
DIALS 2.dev.537-gfda31cc6d
CCP4 7.0.075
Command line: xia2 nproc=1 /Users/graeme/data/i04_bag_training/
Error: Pickling of "dxtbx_masking_ext.GoniometerShadowMasker" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
Grey-Area xia2-316-1 :( $ cat xia2.error 
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 372, in run
    xia2_main()
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 54, in xia2_main
    CommandLine = get_command_line()
  File "/Users/graeme/svn/cctbx/modules/xia2/Applications/xia2_main.py", line 115, in get_command_line
    CommandLine.set_xinfo(xinfo)
  File "/Users/graeme/svn/cctbx/modules/xia2/Handlers/CommandLine.py", line 523, in set_xinfo
    self._xinfo = XProject(xinfo)
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XProject.py", line 36, in __init__
    self.setup_from_xinfo_file(xinfo_file)
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XProject.py", line 348, in setup_from_xinfo_file
    excluded_regions=sweep_info.get("excluded_regions", []),
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XWavelength.py", line 267, in add_sweep
    excluded_regions=excluded_regions,
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XSweep.py", line 231, in __init__
    self._imageset = copy.deepcopy(imagesets[0])
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 328, in _reconstruct
    args = deepcopy(args, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 328, in _reconstruct
    args = deepcopy(args, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
RuntimeError: Pickling of "dxtbx_masking_ext.GoniometerShadowMasker" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
```

**Comment by graeme-winter** [comment]
Using `dynamic_shadow=0` allows working around for the moment

**Comment by graeme-winter** [comment]
Fixed via upstream by @jmp1985
