### ISSUE TITLE
xia2 / DIALS on MAD data fails (> 1 sweep for 1 wavelength)

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#327]
Data consists of 4 sweeps with two at the peak wavelength:

```
BEGIN PROJECT AUTOMATIC
BEGIN CRYSTAL DEFAULT

BEGIN HA_INFO
ATOM s
END HA_INFO

BEGIN WAVELENGTH WAVE1
WAVELENGTH 0.961118
END WAVELENGTH WAVE1

BEGIN WAVELENGTH WAVE2
WAVELENGTH 0.979493
END WAVELENGTH WAVE2

BEGIN WAVELENGTH WAVE3
WAVELENGTH 0.979183
END WAVELENGTH WAVE3

BEGIN SWEEP SWEEP1
WAVELENGTH WAVE1
DIRECTORY /dls/mx-scratch/dials/mad-low-resolution-eiger
IMAGE sgc-061_8-hrm_1_master.h5
START_END 1 3600
END SWEEP SWEEP1

BEGIN SWEEP SWEEP2
WAVELENGTH WAVE2
DIRECTORY /dls/mx-scratch/dials/mad-low-resolution-eiger
IMAGE sgc-061_8-if_1_master.h5
START_END 1 3600
END SWEEP SWEEP2

BEGIN SWEEP SWEEP3
WAVELENGTH WAVE3
DIRECTORY /dls/mx-scratch/dials/mad-low-resolution-eiger
IMAGE sgc-061_8-pk_1_master.h5
START_END 1 3600
END SWEEP SWEEP3

BEGIN SWEEP SWEEP4
WAVELENGTH WAVE3
DIRECTORY /dls/mx-scratch/dials/mad-low-resolution-eiger
IMAGE sgc-061_8-pk_2_master.h5
START_END 1 3600
END SWEEP SWEEP4

END CRYSTAL DEFAULT
END PROJECT AUTOMATIC
```

Suspect that this has broken some logic in wrangling datasets / sweeps - so a useful test:

```
--------------------- Scaling DEFAULT ----------------------
Completed a round of scaling using dials.scale
---------------- Systematic absences check -----------------
Most likely space group: P 41 21 2
Error: list index out of range
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

and

```
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190909/build/../modules/xia2/command_line/xia2_main.py", line 365, in run
    xia2_main()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190909/build/../modules/xia2/command_line/xia2_main.py", line 272, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190909/modules/xia2/Schema/XProject.py", line 131, in get_output
    result += self._crystals[crystal].get_output()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190909/modules/xia2/Schema/XCrystal.py", line 507, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190909/modules/xia2/Schema/XCrystal.py", line 952, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190909/modules/xia2/Schema/Interfaces/Scaler.py", line 668, in get_scaled_merged_reflections
    self.scale()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190909/modules/xia2/Schema/Interfaces/Scaler.py", line 644, in scale
    self._scalr_result = self._scale()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190909/modules/xia2/Modules/Scaler/DialsScaler.py", line 639, in _scale
    sorted_dnames_by_wl = [dnames_set[i] for i in wl_sort]
  File "lib/orderedset/_orderedset.pyx", line 443, in orderedset._orderedset._OrderedSet.__getitem__
  File "lib/orderedset/_orderedset.pyx", line 421, in orderedset._orderedset._OrderedSet._getindex
IndexError: list index out of range
```

**Comment by graeme-winter** [comment]
For verification running with only 3 sets to ensure that this works right.
