### ISSUE TITLE
miller_array HKL export falling over in CommonScaler

### ISSUE THREAD

**Issue by benjaminhwilliams** [xia2/xia2#334]
This is actually an iotbx bug, a regression introduced recently in https://github.com/cctbx/cctbx_project/commit/4a7e1484d8db4c31d9d0189c7be0a9cf8cdb4e64, and I will submit a PR there to fix it.

```
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/command_line/xia2_main.py", line 365, in run
    xia2_main()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/command_line/xia2_main.py", line 272, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/Schema/XProject.py", line 131, in get_output
    result += self._crystals[crystal].get_output()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/Schema/XCrystal.py", line 507, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/Schema/XCrystal.py", line 952, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/Schema/Interfaces/Scaler.py", line 668, in get_scaled_merged_reflections
    self.scale()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/Schema/Interfaces/Scaler.py", line 647, in scale
    self._scale_finish()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/Modules/Scaler/CommonScaler.py", line 556, in _scale_finish
    self._scale_finish_export_shelxt()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/xia2/Modules/Scaler/CommonScaler.py", line 795, in _scale_finish_export_shelxt
    normalise_if_format_overflow=True,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/cctbx_project/iotbx/shelx/hklf.py", line 88, in miller_array_export_as_shelx_hklf
    line = fmt_3i4(h) + fmt_f8(data[i]*scale) + fmt_f8(s*scale)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190927/modules/cctbx_project/iotbx/shelx/hklf.py", line 69, in fmt_f8
    assert len(result) == 8
AssertionError
```

**Comment by benjaminhwilliams** [comment]
Presumably a test in xia2 that catches this would also be helpful.  It seems only to occur in the case that the scale factor is outside the range (-9999.0, 9999.0) ≈ (-10⁴, 10⁴), so we just need a test dataset that consistently gives such a scale factor.  @jbeilstenedmands, is my understanding correct?

@Anthchirp, if SHELXL doesn't read values greater than 9999 (see https://github.com/xia2/xia2/blob/11344fe03da3bfc3ab4117682bbfb341058b61aa/Modules/Scaler/CommonScaler.py#L787-L796), why is the default in iotbx to restrict the scale to the more permissive range (-99999.0, 999999.0) ≈ (-10⁵, 10⁶) (see https://github.com/cctbx/cctbx_project/blob/561032fcad062b66078bd5e6a2f6da4f95129827/iotbx/shelx/hklf.py#L42-L47)?

**Comment by Anthchirp** [comment]
past me (https://github.com/cctbx/cctbx_project/commit/21266870415cea92bab333460fb158daf33b58eb) probably knew that. I think the range restriction I put in was for writing the files, as the numbers otherwise exceed the column width and then mess up all following fixed width fields.
It may be that what SHELX then does with the values was not on my list of priorities at the time.

**Comment by jbeilstenedmands** [comment]
@benjaminhwilliams As far as I understand the code, the scaling referred to by scale_range is the range into which the intensity, sigma values must be scaled down to, so we'd need a test dataset which consistently gave intensities or sigmas outside of the range (not the scale factor in a dials.scale/Aimless context).

**Comment by benjaminhwilliams** [comment]
@Anthchirp — OK, I too do not really care.

@jbeilstenedmands, thanks, I honestly couldn't be bothered to read far enough into the code to find out what `scale_range` really meant.  I think I may have at least one such test data set.
