### ISSUE TITLE
xia2.rogues_gallery broken

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#352]
`$ xia2.rogues_gallery `
```python
Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/xia2/command_line/rogues_gallery.py", line 153, in <module>
    reconstruct_rogues(params.rogues)
  File "/scratch/wra62962/files/dials/build/../modules/xia2/command_line/rogues_gallery.py", line 44, in reconstruct_rogues
    epochs = scaler._sweep_handler.get_epochs()
AttributeError: 'NoneType' object has no attribute 'get_epochs'
```

**Comment by rjgildea** [comment]
> Could be we should have a list of these kinds of mini-projects for students to do if someone asks?

Or keep a list somewhere of "Good first issues" for newcomers (internal or external) that would like to try their hand at DIALS development? Could be a label in GitHub?
https://help.github.com/en/github/building-a-strong-community/helping-new-contributors-find-your-project-with-labels

**Comment by graeme-winter** [comment]
It is gone, closing
