### ISSUE TITLE
ctruncate failure on narrow wedge in dials-full pipeline

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#359]
After resolution of #357, this dataset now fails after running ctruncate:

```
$ xia2 pipeline=dials min_images=3 project=AUTOMATIC crystal=DEFAULT read_all_image_headers=False atom=S image=/dls/i03/data/2019/nt18231-17/tmp/2019-11-06/18-30-46-46006256/ProtK_InSitu_Au_47_9_1_0001.cbf:1:25 dynamic_shadowing=False resolution.cc_half_significance_level=0.1
...
-------------------- Preparing DEFAULT ---------------------
--------------------- Scaling DEFAULT ----------------------
Completed a round of scaling using dials.scale
Resolution for sweep SAD/SWEEP1: 6.60 (cc_half > 0.3)
--------------------- Scaling DEFAULT ----------------------
Completed a round of scaling using dials.scale
---------------- Systematic absences check -----------------
Most likely space group: P 4
------------------- Unit cell refinement -------------------
Overall:  68.48  68.48 104.64  90.00  90.00  90.00
Error: ctruncate failure
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

```
$ cat xia2.error 
Traceback (most recent call last):
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 360, in run
    xia2_main()
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 267, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/dls/science/users/hko55533/software/cctbx/modules/xia2/Schema/XProject.py", line 114, in get_output
    result += self._crystals[crystal].get_output()
  File "/dls/science/users/hko55533/software/cctbx/modules/xia2/Schema/XCrystal.py", line 435, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/dls/science/users/hko55533/software/cctbx/modules/xia2/Schema/XCrystal.py", line 823, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/dls/science/users/hko55533/software/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 655, in get_scaled_merged_reflections
    self.scale()
  File "/dls/science/users/hko55533/software/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 634, in scale
    self._scale_finish()
  File "/dls/science/users/hko55533/software/cctbx/modules/xia2/Modules/Scaler/CommonScaler.py", line 539, in _scale_finish
    self._scale_finish_chunk_3_truncate()
  File "/dls/science/users/hko55533/software/cctbx/modules/xia2/Modules/Scaler/CommonScaler.py", line 663, in _scale_finish_chunk_3_truncate
    truncate.truncate()
  File "/dls/science/users/hko55533/software/cctbx/modules/xia2/Wrappers/CCP4/Ctruncate.py", line 99, in truncate
    raise RuntimeError("ctruncate failure")
RuntimeError: ctruncate failure
```

ctruncate log file: `/dls/tmp/rjgildea/357/DEFAULT/scale/23_ctruncate.log`

**Comment by rjgildea** [comment]
[23_ctruncate.log](https://github.com/xia2/xia2/files/3819472/23_ctruncate.log)

**Comment by jbeilstenedmands** [comment]
Now that we have dials.merge which calls the ctruncate routines from cctbx, perhaps we can replace the use of ccp4 ctruncate with dials.merge?

**Comment by rjgildea** [comment]
If dials.merge is already running the truncate routines, why are we running both dials.merge and ctruncate? We also have the xia2 option `truncate=cctbx`, with the addition of which the xia2 command above succeeds...
