### ISSUE TITLE
xia2 pipeline=dials scaler=ccp4a fails

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#363]
This works as expected:
```
$ xia2 pipeline=dials-aimless $(dials.data get -q x4wide)
```
but this fails even though it should be functionally equivalent (as far as I can tell):
```
$ xia2 pipeline=dials scaler=ccp4a $(dials.data get -q x4wide)
...
-------------------- Preparing DEFAULT ---------------------
Error: '/Users/rjgildea/tmp/Z/DEFAULT/NATIVE/SWEEP1/integrate/13_integrated.refl'
```

```
$ cat xia2.error 
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 365, in run
    xia2_main()
  File "/Users/rjgildea/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 272, in xia2_main
    Chatter.write(xinfo.get_output(), strip=False)
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/XProject.py", line 131, in get_output
    result += self._crystals[crystal].get_output()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/XCrystal.py", line 507, in get_output
    reflections_all = self.get_scaled_merged_reflections()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/XCrystal.py", line 952, in get_scaled_merged_reflections
    return self._get_scaler().get_scaled_merged_reflections()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 668, in get_scaled_merged_reflections
    self.scale()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/Interfaces/Scaler.py", line 639, in scale
    self._scale_prepare()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Modules/Scaler/CCP4ScalerA.py", line 195, in _scale_prepare
    assert is_mtz_file(si.get_reflections()), repr(si.get_reflections())
AssertionError: '/Users/rjgildea/tmp/Z/DEFAULT/NATIVE/SWEEP1/integrate/13_integrated.refl'
```

**Comment by graeme-winter** [comment]
Should get back as MTZ not DIALS format I guess, must be worked around in the old pipeline? 🤔 you are right though that they _should_ be equivalent.

**Comment by jbeilstenedmands** [comment]
Oops I think this is my fault. I think if the integrater is set to dials, then the default output format is .refl,.expt rather than mtz. See 8dbb38f

**Comment by graeme-winter** [comment]
That smells about right 😉

**Comment by rjgildea** [comment]
I suspect the issue is this line:
https://github.com/xia2/xia2/blob/c3c89b5b94be07a900afc02a8fb96e3f1f8af753/Modules/Integrater/IntegraterFactory.py#L105-L106
It should be checking for the scaler, not the pipeline.
