### ISSUE TITLE
xia2.multiplex max_clusters= option broken

### ISSUE THREAD

**Issue by rjgildea** [xia2/xia2#404]
Probably by experiment identifiers changes:

```
$ xia2.multiplex $(dials.data get -q multi_crystal_proteinase_k)/*.{json,pickle} dose=1,20 max_clusters=2
...
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/xia2/command_line/multiplex.py", line 122, in <module>
    run(sys.argv[1:])
  File "/Users/rjgildea/software/cctbx/build/../modules/xia2/command_line/multiplex.py", line 116, in run
    ScaleAndMerge.MultiCrystalScale(experiments, reflections_all, params)
  File "/Users/rjgildea/software/cctbx/modules/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 441, in __init__
    data_manager.select(cluster.labels)
  File "/Users/rjgildea/software/cctbx/modules/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 217, in select
    experiment_identifiers
  File "/Users/rjgildea/software/cctbx/modules/dials/array_family/flex.py", line 1255, in select_on_experiment_identifiers
    % (list_of_identifiers, id_values)
KeyError: "Not all requested identifiers\nfound in the table's map, has the experiment_identifiers() map been created?\nRequested [0, 1, 2, 3, 4, 6]:\nFound []"
```

**Comment by rjgildea** [comment]
This change now sets the ids as the labels, not the identifiers:
https://github.com/xia2/xia2/commit/c54e1b3d25f32d8325a2b69d54c05e9695598e08#diff-47673d01a8e657e0f5d36767be1f7321R108
however these labels are later used to select on identifiers, which now fails, as they aren't in fact identifiers:
https://github.com/xia2/xia2/blob/0de1b9317357552640b8d04834bb16642c7de39b/Modules/MultiCrystal/ScaleAndMerge.py#L440
