### ISSUE TITLE
Worth running refinement after integration?

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#44]
Hmmm.... while we are here also seems to make a lot of difference to applying the refinement after integration using the good centroids i.e. filter for strong && integrated gives _fantastic_ improvement in RMSD:

```
------------------------------------------------
| Step | Nref | RMSD_X   | RMSD_Y   | RMSD_Phi |
|      |      | (mm)     | (mm)     | (deg)    |
------------------------------------------------
| 0    | 1234 | 0.85004  | 1.2543   | 0.18753  |
| 1    | 1234 | 0.12486  | 0.13739  | 0.17553  |
| 2    | 1234 | 0.11399  | 0.12801  | 0.16604  |
| 3    | 1234 | 0.099415 | 0.11186  | 0.14233  |
| 4    | 1234 | 0.075066 | 0.079777 | 0.09627  |
| 5    | 1234 | 0.054283 | 0.046631 | 0.044695 |
| 6    | 1234 | 0.050306 | 0.037329 | 0.025557 |
| 7    | 1234 | 0.050357 | 0.036943 | 0.024515 |
| 8    | 1234 | 0.050373 | 0.036937 | 0.024499 |
| 9    | 1234 | 0.050373 | 0.036937 | 0.024498 |
------------------------------------------------
RMSD no longer decreasing

RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 1234 | 0.29287 | 0.21475 | 0.24498  |
---------------------------------------------
```

Should this also be a feature of xia2 i.e. global refinement after processing & reintegration c/f old deadly

**Comment by graeme-winter** [comment]
This will need a tool to filter the reflections so we get the strong & integrated ones to use for this refinement, then some adjustment of the integration loops within xia2 to work like the XDS one; however first need to demonstrate that it makes things better

**Comment by rjgildea** [comment]
> however first need to demonstrate that it makes things better

This. Until we get to that stage, primarily a DIALS issue rather than xia2...

**Comment by graeme-winter** [comment]
I am not sure I totally agree - we *can* do it in DIALS right now so it's a non-issue, the question of do or do not is for xia2 right? Maybe a dials documentation issue if we demonstrate it makes things better...

**Comment by graeme-winter** [comment]
Interesting:

```
dev.dials.filter_reflections inclusions.flag=strong inclusions.flag=integrated 20_integrated.pickle 
dials.refine 20_integrated_experiments.json filtered.pickle 
dials.integrate refined* nproc=8
```

Makes dials.integrate go boom; could be that this is expected...

```
Calculating E.S.D Reflecting Range.
 sigma b: 0.000000 degrees
 sigma m: 0.320388 degrees
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 498, in <module>
    halraiser(e)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 496, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 269, in run
    experiments = ProfileModelFactory.create(params, experiments, reference)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/factory.py", line 55, in create
    expr.scan)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 244, in create
    sigma_m=calculator.sigma_m())
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 100, in __init__
    assert(self._sigma_b > 0)
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

**Comment by graeme-winter** [comment]
Passing in the original refined.pickle works.... wait is this obvious, since it does not have the shoeboxes in the refection file (duh) hmmm had to fix bug in extract shoeboxes to test hypothesis.... OK, this now works; extracting shoeboxes expensive step though, perhaps should filter then extract shoeboxes or copy shoeboxes across since all reflections should be in strong.pickle.

**Comment by graeme-winter** [comment]
OK, interesting this *does* make a measurable difference in the case of the small molecule example I tried just here: 

"Screening run" from L-cyst data scaled with defaults:

```
<!--SUMMARY_BEGIN--> $TEXT:Result: $$ $$
Summary data for        Project: DIALS Crystal: XTAL Dataset: FROMDIALS

                                           Overall  InnerShell  OuterShell
Low resolution limit                        6.74      6.74      0.92
High resolution limit                       0.82      1.84      0.82

Rmerge  (within I+/I-)                     0.019     0.015     0.026
Rmerge  (all I+ and I-)                    0.021     0.016     0.028
Rmeas (within I+/I-)                       0.023     0.018     0.035
Rmeas (all I+ & I-)                        0.024     0.018     0.035
Rpim (within I+/I-)                        0.013     0.010     0.024
Rpim (all I+ & I-)                         0.011     0.009     0.021
Rmerge in top intensity bin                0.016        -         - 
Total number of observations                2289       285       178
Total number unique                          518        67        75
Mean((I)/sd(I))                             47.6      61.2      23.7
Mn(I) half-set correlation CC(1/2)         0.999     1.000     0.998
Completeness                                82.7      99.4      46.1
Multiplicity                                 4.4       4.3       2.4
```

And the same from recycling (inc. extract shoeboxes) re-refine && reintegrate:

```
Summary data for        Project: DIALS Crystal: XTAL Dataset: FROMDIALS

                                           Overall  InnerShell  OuterShell
Low resolution limit                       12.02     12.02      0.92
High resolution limit                       0.82      1.84      0.82

Rmerge  (within I+/I-)                     0.017     0.016     0.022
Rmerge  (all I+ and I-)                    0.019     0.017     0.023
Rmeas (within I+/I-)                       0.021     0.019     0.029
Rmeas (all I+ & I-)                        0.022     0.020     0.028
Rpim (within I+/I-)                        0.012     0.011     0.020
Rpim (all I+ & I-)                         0.010     0.010     0.017
Rmerge in top intensity bin                0.017        -         - 
Total number of observations                2056       275       137
Total number unique                          498        69        60
Mean((I)/sd(I))                             51.5      67.2      25.4
Mn(I) half-set correlation CC(1/2)         1.000     1.000     0.999
Completeness                                80.1      99.4      37.8
Multiplicity                                 4.1       4.0       2.3
```

Higher I/sig(I) but lower completeness; very interesting

integrate logs summary original:

```
 ----------------------------------------------------------------
 Item                                  | Overall | Low    | High
 ----------------------------------------------------------------
 dmin                                  | 0.82    | 2.19   | 0.82
 dmax                                  | 6.81    | 6.81   | 0.83
 number fully recorded                 | 2663    | 212    | 3
 number partially recorded             | 80      | 10     | 0
 number with invalid background pixels | 494     | 37     | 3
 number with invalid foreground pixels | 330     | 28     | 1
 number with overloaded pixels         | 0       | 0      | 0
 number in powder rings                | 0       | 0      | 0
 number processed with summation       | 2389    | 194    | 2
 number processed with profile fitting | 2342    | 188    | 0
 number failed in background modelling | 31      | 8      | 0
 number failed in summation            | 330     | 28     | 1
 number failed in profile fitting      | 377     | 34     | 3
 ibg                                   | 0.06    | 0.16   | 0.02
 i/sigi (summation)                    | 56.76   | 159.81 | 22.59
 i/sigi (profile fitting)              | 55.53   | 159.77 | 0.00
 cc prf                                | 0.85    | 0.77   | 0.00
 cc_pearson sum/prf                    | 1.00    | 1.00   | 0.00
 cc_spearman sum/prf                   | 1.00    | 1.00   | 0.00
 ----------------------------------------------------------------

```

Recycled

```
 ---------------------------------------------------------------
 Item                                  | Overall | Low    | High
 ---------------------------------------------------------------
 dmin                                  | 0.82    | 2.21   | 0.82
 dmax                                  | 12.15   | 12.15  | 0.83
 number fully recorded                 | 2653    | 217    | 3
 number partially recorded             | 113     | 5      | 0
 number with invalid background pixels | 950     | 64     | 3
 number with invalid foreground pixels | 504     | 40     | 3
 number with overloaded pixels         | 0       | 0      | 0
 number in powder rings                | 0       | 0      | 0
 number processed with summation       | 2215    | 182    | 0
 number processed with profile fitting | 2118    | 181    | 0
 number failed in background modelling | 0       | 0      | 0
 number failed in summation            | 504     | 40     | 3
 number failed in profile fitting      | 601     | 41     | 3
 ibg                                   | 0.03    | 0.08   | 0.00
 i/sigi (summation)                    | 56.62   | 156.12 | 0.00
 i/sigi (profile fitting)              | 56.69   | 152.75 | 0.00
 cc prf                                | 0.93    | 0.89   | 0.00
 cc_pearson sum/prf                    | 1.00    | 1.00   | 0.00
 cc_spearman sum/prf                   | 1.00    | 1.00   | 0.00
 ---------------------------------------------------------------
```

i.e. better profile correlations... as one may expect

**Comment by graeme-winter** [comment]
BTW RMSD's for scan varying re-refinement:

```
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 1234 | 0.16589 | 0.16396 | 0.12356  |
---------------------------------------------
```

**Comment by graeme-winter** [comment]
Seems one can also split the difference by using the same input reflections as before with the re-refined experiments.json (i.e. not messing with the extracting of shoeboxes) 

Gives

```
Summary data for        Project: DIALS Crystal: XTAL Dataset: FROMDIALS

                                           Overall  InnerShell  OuterShell
Low resolution limit                       12.02     12.02      0.92
High resolution limit                       0.82      1.84      0.82

Rmerge  (within I+/I-)                     0.018     0.015     0.030
Rmerge  (all I+ and I-)                    0.020     0.016     0.032
Rmeas (within I+/I-)                       0.022     0.018     0.042
Rmeas (all I+ & I-)                        0.023     0.018     0.041
Rpim (within I+/I-)                        0.012     0.010     0.028
Rpim (all I+ & I-)                         0.011     0.009     0.024
Rmerge in top intensity bin                0.017        -         - 
Total number of observations                2290       289       180
Total number unique                          520        69        75
Mean((I)/sd(I))                             46.6      63.7      21.6
Mn(I) half-set correlation CC(1/2)         0.999     1.000     0.996
Completeness                                82.7      99.4      46.1
Multiplicity                                 4.4       4.2       2.4
```

compared with 

```
Summary data for        Project: DIALS Crystal: XTAL Dataset: FROMDIALS

                                           Overall  InnerShell  OuterShell
Low resolution limit                        6.74      6.74      0.92
High resolution limit                       0.82      1.84      0.82

Rmerge  (within I+/I-)                     0.019     0.015     0.026
Rmerge  (all I+ and I-)                    0.021     0.016     0.028
Rmeas (within I+/I-)                       0.023     0.018     0.035
Rmeas (all I+ & I-)                        0.024     0.018     0.035
Rpim (within I+/I-)                        0.013     0.010     0.024
Rpim (all I+ & I-)                         0.011     0.009     0.021
Rmerge in top intensity bin                0.016        -         - 
Total number of observations                2289       285       178
Total number unique                          518        67        75
Mean((I)/sd(I))                             47.6      61.2      23.7
Mn(I) half-set correlation CC(1/2)         0.999     1.000     0.998
Completeness                                82.7      99.4      46.1
Multiplicity                                 4.4       4.3       2.4
```

from the first pass

Conclusions are not obvious, though perhaps this data are too good to evaluate?

**Comment by graeme-winter** [comment]
@dagewa hindsight suggests to me that this could be an important thing for evaluating detector metrology... what do you think?

**Comment by dagewa** [comment]
Yes, agreed. We never did finish the detector metrology investigations. One problem was the fact that profile modelling doesn't work nicely for a multi panel detector. So unless you bake the shifts into the pixel/mm mapping (losing third dimension, if that at all important) then you can't really benefit from them.

**Comment by graeme-winter** [comment]
Indeed - however even using the summation integrated centroids would probably be an improvement over using the strong reflections-with-background as centroids to run the metrology refinement against? I agree that to use the final results of the refinement would take a bit more work i.e. the baking in you describe...

**Comment by dagewa** [comment]
Yes you're right that doing the refinement is no problem. It's just how to use that information afterwards. I think it is worth setting time aside to review what datasets we've got for this for each detector and how best to go about it. I suggest meeting up to do this, but after the ESRF and ACA trips may be best.

**Comment by graeme-winter** [comment]
Looking at an MX example set for this - initial refinement

```
----------------------------------------------
| Exp | Nref  | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |       | (px)    | (px)    | (images) |
----------------------------------------------
| 0   | 15404 | 0.25064 | 0.18808 | 0.13619  |
----------------------------------------------
```

post-integration-refinement

```
-----------------------------------------------
| Exp | Nref   | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |        | (px)    | (px)    | (images) |
-----------------------------------------------
| 0   | 211213 | 0.18424 | 0.14094 | 0.11574  |
-----------------------------------------------
```

**Comment by graeme-winter** [comment]
```
dials.import ../data/*cbf
dials.find_spots datablock.json nproc=20
dials.index datablock.json strong.pickle space_group=P4
dials.refine indexed.pickle experiments.json scan_varying=true bin_size_fraction=0
dials.integrate refined* nproc=20
mkdir ../1; cd ../1
cp ../0/integrated_experiments.json .
dev.dials.filter_reflections inclusions.flag=strong inclusions.flag=integrated ../0/integrated.pickle 
dials.refine integrated_experiments.json filtered.pickle scan_varying=true bin_size_fraction=0
dev.dials.extract_shoeboxes refined*
dials.integrate refined_experiments.json shoeboxes.pickle nproc=20
```

Initial integration run:

```
 ---------------------------------------------------------------
 Item                                  | Overall | Low    | High
 ---------------------------------------------------------------
 dmin                                  | 1.24    | 3.35   | 1.24
 dmax                                  | 122.09  | 122.09 | 1.26
 number fully recorded                 | 1068760 | 78202  | 797
 number partially recorded             | 24766   | 1991   | 4
 number with invalid background pixels | 211825  | 13589  | 639
 number with invalid foreground pixels | 135838  | 9899   | 261
 number with overloaded pixels         | 26      | 26     | 0
 number in powder rings                | 0       | 0      | 0
 number processed with summation       | 950911  | 69904  | 540
 number processed with profile fitting | 940542  | 69598  | 342
 number failed in background modelling | 19890   | 3088   | 0
 number failed in summation            | 135838  | 9899   | 261
 number failed in profile fitting      | 146207  | 10205  | 459
 ibg                                   | 1.04    | 2.85   | 0.20
 i/sigi (summation)                    | 5.48    | 35.98  | 0.02
 i/sigi (profile fitting)              | 6.48    | 37.75  | 0.07
 cc prf                                | 0.36    | 0.70   | 0.01
 cc_pearson sum/prf                    | 1.00    | 1.00   | 0.37
 cc_spearman sum/prf                   | 0.88    | 1.00   | 0.34
 ---------------------------------------------------------------
```

**Comment by graeme-winter** [comment]
@jmp1985  comment here - this seems to really use a lot of RAM

```
 7846 gw56      20   0 19.9g  19g 8912 R 100.0 15.6   0:41.97 python2.7         
 7844 gw56      20   0 19.5g  19g 8960 R 100.0 15.2   0:42.13 python2.7         
 7847 gw56      20   0 20.2g  19g 8912 R 99.7 15.7   0:41.98 python2.7          
 7845 gw56      20   0 19.9g  19g 8912 R 98.0 15.6   0:41.94 python2.7   
```

even on stonking big node only using 4 threads... odd it is using so much more ram.

Initial model

```
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.027551 degrees
 sigma m: 0.108679 degrees
```

Recycle model:

```
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.168514 degrees
 sigma m: 0.215254 degrees
```

ah reflections being integrated as being *much* bigger... could be an unexpected result

**Comment by graeme-winter** [comment]
0-order - setting original refined reflections as input with recycled-refined model for integration makes essentially no difference in this example - integrated intensities nearly identical. Still waiting on the big model processing...

**Comment by graeme-winter** [comment]
Small molecule example referenced at start of this log:

```
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.044950 degrees
 sigma m: 0.171391 degrees
```

original, to 

```
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.116147 degrees
 sigma m: 0.320045 degrees
```

from the integrated data i.e. roughly doubling in all directions - using these settings makes for very small profiles:

```
0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 3 0 0 0 0 0 
0 0 0 0 6 Z 4 0 0 0 0 
0 0 0 0 1 8 1 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 
```

- thinking about this overnight @jmp1985 there is not good reason why this is the case because in theory they are starting from the same pixel data, the only thing I could think was the bigger shoebox (since this now includes background) somehow messes with the algorithm.
