### ISSUE TITLE
xia2 loses gain information during serialization/deserialization

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#45]
```xia2 -small_molecule $(libtbx.show_build_path)/xia2_regression/test_data/i19_sucrose``` fails.
```xia2 -small_molecule $(libtbx.show_build_path)/xia2_regression/test_data/i19_sucrose nproc=1``` works

Cause of this is that the detector gain setting, originally set in dxtbx, is lost while joining the subprocesses.

**Comment by Anthchirp** [comment]
to run example need updated cctbx, use xia2 branch ```xia2-45```

**Comment by rjgildea** [comment]
gain is lost on serialization/deserialization of dxtbx object:

```
$ dials.python tst.py $(libtbx.show_build_path)/xia2_regression/test_data/i19_sucrose/sugar11*.img
Traceback (most recent call last):
  File "tst.py", line 1, in <module>
    def run(args):
  File "tst.py", line 8, in run
    assert d1[0].get_gain() == d2[0].get_gain(), (d1[0].get_gain(), d2[0].get_gain())
AssertionError: (10.0, 1.0)
```

```
$ cat tst.py
def run(args):
  from dxtbx.datablock import DataBlockFactory
  datablock = DataBlockFactory.from_args(args)[0]
  imageset = datablock.extract_imagesets()[0]
  d1 = imageset.get_detector()
  import cPickle
  d2 = cPickle.loads(cPickle.dumps(d1))
  assert d1[0].get_gain() == d2[0].get_gain(), (d1[0].get_gain(), d2[0].get_gain())

if __name__ == '__main__':
  import sys
  run(sys.argv[1:])
```

**Comment by rjgildea** [comment]
@jmp1985 please could you take a look at this?
