### ISSUE TITLE
Status: error "float argument required, not NoneType"

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#46]
```
$ xia2 -small_molecule d_min=0.75 space_group=P2 "unit_cell=17.49 7.48 19.53 90.0 104.9 90.0" /dls/i19-1/data/2016/sw13258-6/DI0063a
(...)
Scaled reflections (NATIVE): /dls/tmp/wra62962/directories/qjuug9ze/DataFiles/AUTOMATIC_DEFAULT_scaled.sca
sca_unmerged format:
Scaled reflections (NATIVE): /dls/tmp/wra62962/directories/qjuug9ze/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.sca
Processing took 00h 21m 13s
Status: error "float argument required, not NoneType"
```
```
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20160706/build/../modules/xia2/command_line/xia2_main.py", line 283, in run
    xinfo = xia2_main()
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20160706/build/../modules/xia2/command_line/xia2_main.py", line 251, in xia2_main
    summary_records = xinfo.summarise()
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20160706/modules/xia2/Schema/XProject.py", line 142, in summarise
    for record in self._crystals[crystal].summarise():
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20160706/modules/xia2/Schema/XCrystal.py", line 563, in summarise
    for record in self._wavelengths[wavelength].summarise():
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20160706/modules/xia2/Schema/XWavelength.py", line 167, in summarise
    for record in s.summarise():
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20160706/modules/xia2/Schema/XSweep.py", line 560, in summarise
    (hbeam[0], hbeam[1], ibeam[0], ibeam[1]))
TypeError: float argument required, not NoneType
```

**Comment by Anthchirp** [comment]
I think this may be caused by or be related to dials/dials#167

**Comment by Anthchirp** [comment]
More likely caused by 2theta >= 90, in this particular case for that sweep 2theta=105°

**Comment by graeme-winter** [comment]
I think this is fine, since we should not really be relying on thsi so much
anyhow (maybe write beam not on detector, or something)
