### ISSUE TITLE
3 wavelength MAD + each wavelength taken twice breaks assumptions?

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#494]
Ran, worked fine, failed at the end

```
Scaled reflections (WAVE1): /dls/i04/data/2020/mx27124-1/processing/gw56/SeThau-mad-both/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE1.mtz
Scaled reflections (WAVE3): /dls/i04/data/2020/mx27124-1/processing/gw56/SeThau-mad-both/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE3.mtz
Scaled reflections (WAVE2): /dls/i04/data/2020/mx27124-1/processing/gw56/SeThau-mad-both/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged_WAVE2.mtz
mtz format:
Scaled reflections: /dls/i04/data/2020/mx27124-1/processing/gw56/SeThau-mad-both/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_free.mtz
Error: 
Please send the contents of xia2.txt, xia2-error.txt and xia2-debug.txt to:
xia2.support@gmail.com
Silver-Surfer xia2-dials-all :) $ cat xia2-error.txt 
Traceback (most recent call last):
  File "/dls/science/users/gw56/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 334, in run
    xia2_main()
  File "/dls/science/users/gw56/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 291, in xia2_main
    xinfo, filename="xia2.html", params=params.xia2.settings.report
  File "/dls/science/users/gw56/cctbx/modules/xia2/command_line/html.py", line 129, in generate_xia2_html
    json_data.update(report.batch_dependent_plots())
  File "/dls/science/users/gw56/cctbx/modules/xia2/Modules/Report/__init__.py", line 198, in batch_dependent_plots
    bm = batch_manager(binned_batches, batches)
  File "/dls/science/users/gw56/cctbx/modules/dials/util/batch_handling.py", line 17, in __init__
    self.reduced_batches, self._batch_increments = self._reduce()
  File "/dls/science/users/gw56/cctbx/modules/dials/util/batch_handling.py", line 32, in _reduce
    assert len(set(reduced_batches)) == len(reduced_batches)
AssertionError
```

**Comment by graeme-winter** [comment]
Possibly related: something funny happening in reflection file sizes (see `split_?`)

```
Silver-Surfer xia2-dials-all :( $ find . -name '*refl' | xargs du -k | sort -n | awk '{print $2}' | xargs du -ach
5.8M	./DEFAULT/WAVE3/SWEEP5/integrate/reference_profiles.refl
5.9M	./DEFAULT/WAVE1/SWEEP1/integrate/reference_profiles.refl
5.9M	./DEFAULT/WAVE2/SWEEP3/integrate/reference_profiles.refl
6.0M	./DEFAULT/WAVE3/SWEEP6/integrate/reference_profiles.refl
6.1M	./DEFAULT/WAVE1/SWEEP2/integrate/reference_profiles.refl
6.1M	./DEFAULT/WAVE2/SWEEP4/integrate/reference_profiles.refl
153M	./DEFAULT/WAVE1/SWEEP1/index/7_reindexed.refl
157M	./DEFAULT/WAVE3/SWEEP5/index/55_reindexed.refl
159M	./DEFAULT/WAVE1/SWEEP2/index/19_reindexed.refl
161M	./DEFAULT/WAVE2/SWEEP3/index/31_reindexed.refl
165M	./DEFAULT/WAVE3/SWEEP6/index/67_reindexed.refl
168M	./DEFAULT/WAVE2/SWEEP4/index/43_reindexed.refl
219M	./DEFAULT/WAVE1/SWEEP1/index/2_SWEEP1_strong.refl
226M	./DEFAULT/WAVE1/SWEEP2/index/14_SWEEP2_strong.refl
227M	./DEFAULT/WAVE3/SWEEP5/index/50_SWEEP5_strong.refl
233M	./DEFAULT/WAVE2/SWEEP3/index/26_SWEEP3_strong.refl
236M	./DEFAULT/WAVE3/SWEEP6/index/62_SWEEP6_strong.refl
243M	./DEFAULT/WAVE2/SWEEP4/index/38_SWEEP4_strong.refl
262M	./DEFAULT/WAVE1/SWEEP1/index/4_indexed.refl
262M	./DEFAULT/WAVE1/SWEEP1/refine/8_refined.refl
262M	./DEFAULT/WAVE1/SWEEP1/refine/9_refined.refl
270M	./DEFAULT/WAVE3/SWEEP5/index/52_indexed.refl
270M	./DEFAULT/WAVE3/SWEEP5/refine/56_refined.refl
270M	./DEFAULT/WAVE3/SWEEP5/refine/57_refined.refl
271M	./DEFAULT/WAVE1/SWEEP2/index/16_indexed.refl
271M	./DEFAULT/WAVE1/SWEEP2/refine/20_refined.refl
271M	./DEFAULT/WAVE1/SWEEP2/refine/21_refined.refl
277M	./DEFAULT/WAVE2/SWEEP3/index/28_indexed.refl
277M	./DEFAULT/WAVE2/SWEEP3/refine/32_refined.refl
277M	./DEFAULT/WAVE2/SWEEP3/refine/33_refined.refl
282M	./DEFAULT/WAVE3/SWEEP6/index/64_indexed.refl
282M	./DEFAULT/WAVE3/SWEEP6/refine/68_refined.refl
282M	./DEFAULT/WAVE3/SWEEP6/refine/69_refined.refl
289M	./DEFAULT/WAVE2/SWEEP4/index/40_indexed.refl
289M	./DEFAULT/WAVE2/SWEEP4/refine/44_refined.refl
289M	./DEFAULT/WAVE2/SWEEP4/refine/45_refined.refl
840M	./DEFAULT/WAVE3/SWEEP6/integrate/82_reindexed.refl
840M	./DEFAULT/scale/87_reindexed.refl
840M	./DataFiles/AUTOMATIC_DEFAULT_WAVE3_SWEEP6.refl
841M	./DEFAULT/WAVE3/SWEEP5/integrate/79_reindexed.refl
841M	./DataFiles/AUTOMATIC_DEFAULT_WAVE3_SWEEP5.refl
841M	./DEFAULT/WAVE2/SWEEP3/integrate/80_reindexed.refl
841M	./DEFAULT/scale/85_reindexed.refl
841M	./DataFiles/AUTOMATIC_DEFAULT_WAVE2_SWEEP3.refl
841M	./DEFAULT/WAVE2/SWEEP4/integrate/83_reindexed.refl
841M	./DEFAULT/scale/88_reindexed.refl
841M	./DataFiles/AUTOMATIC_DEFAULT_WAVE2_SWEEP4.refl
841M	./DEFAULT/WAVE1/SWEEP2/integrate/84_reindexed.refl
841M	./DEFAULT/scale/89_reindexed.refl
841M	./DataFiles/AUTOMATIC_DEFAULT_WAVE1_SWEEP2.refl
847M	./DEFAULT/WAVE1/SWEEP1/integrate/81_reindexed.refl
847M	./DEFAULT/scale/86_reindexed.refl
847M	./DataFiles/AUTOMATIC_DEFAULT_WAVE1_SWEEP1.refl
926M	./DEFAULT/scale/split_3.refl
928M	./DEFAULT/scale/split_4.refl
929M	./DEFAULT/scale/split_5.refl
955M	./DEFAULT/WAVE3/SWEEP5/integrate/59_integrated.refl
955M	./DEFAULT/scale/73_symmetrized.refl
956M	./DEFAULT/WAVE2/SWEEP3/integrate/35_integrated.refl
956M	./DEFAULT/scale/74_symmetrized.refl
957M	./DEFAULT/WAVE3/SWEEP6/integrate/71_integrated.refl
957M	./DEFAULT/scale/76_symmetrized.refl
958M	./DEFAULT/WAVE1/SWEEP2/integrate/23_integrated.refl
958M	./DEFAULT/scale/78_symmetrized.refl
960M	./DEFAULT/WAVE2/SWEEP4/integrate/47_integrated.refl
960M	./DEFAULT/scale/77_symmetrized.refl
962M	./DEFAULT/WAVE1/SWEEP1/integrate/11_integrated.refl
962M	./DEFAULT/scale/75_symmetrized.refl
1.8G	./DEFAULT/scale/split_1.refl
1.8G	./DEFAULT/scale/split_2.refl
1.8G	./DEFAULT/scale/split_0.refl
5.4G	./DEFAULT/scale/97_scaled.refl
5.4G	./DEFAULT/scale/98_symmetrized.refl
5.4G	./DataFiles/AUTOMATIC_DEFAULT_scaled.refl
5.5G	./DEFAULT/scale/90_scaled.refl
 62G	total
```

**Comment by graeme-winter** [comment]
Is not lies, is fine, but the files are misleading. 

Two cycles of split_expts - first splits on run (i.e. 0...5) then the second has `by_wavelength = True` so splits on wavelength, but the 3 split files are left around. 

So removing the temporary files would seem like a neat idea, too. Leaving them around is misleading 

```
Silver-Surfer scale :) $ dials.show split_[0-9].refl |  grep "contains"
Reflection list contains 1149094 reflections
Reflection list contains 1146317 reflections
Reflection list contains 1148267 reflections
Reflection list contains 573349 reflections
Reflection list contains 574514 reflections
Reflection list contains 573600 reflections
```
