### ISSUE TITLE
xia2.html not working (for multi-pass MAD?)

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#496]
In context of xia2 job:

```
Silver-Surfer mad :( $ cat xia2-error.txt 
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 334, in run
    xia2_main()
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 291, in xia2_main
    xinfo, filename="xia2.html", params=params.xia2.settings.report
  File "/Users/graeme/svn/cctbx/modules/xia2/command_line/html.py", line 129, in generate_xia2_html
    json_data.update(report.batch_dependent_plots())
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/Report/__init__.py", line 198, in batch_dependent_plots
    bm = batch_manager(binned_batches, batches)
  File "/Users/graeme/svn/cctbx/modules/dials/util/batch_handling.py", line 17, in __init__
    self.reduced_batches, self._batch_increments = self._reduce()
  File "/Users/graeme/svn/cctbx/modules/dials/util/batch_handling.py", line 32, in _reduce
    assert len(set(reduced_batches)) == len(reduced_batches)
AssertionError
```

and stand alone:

```
Silver-Surfer mad :) $ xia2.html
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/html.py", line 78, in generate_xia2_html
    for si in scaler._sweep_information.values():
AttributeError: 'DialsScaler' object has no attribute '_sweep_information'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/html.py", line 589, in <module>
    run(args)
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/html.py", line 25, in run
    generate_xia2_html(xinfo, args=args)
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/html.py", line 84, in generate_xia2_html
    for si in scaler._sweep_handler._sweep_information.values():
AttributeError: 'NoneType' object has no attribute '_sweep_information'
```

**Comment by graeme-winter** [comment]
Run with 
```
xia2 atom=Se read_all=0 trust_beam=1 \
image=/Volumes/Blue2/Data/i04-sethau-mad/SeThau_hrm_2_master.h5:1:900 \
image=/Volumes/Blue2/Data/i04-sethau-mad/SeThau_hrm_3_master.h5:1:900 \
image=/Volumes/Blue2/Data/i04-sethau-mad/SeThau_if_2_master.h5:1:900 \
image=/Volumes/Blue2/Data/i04-sethau-mad/SeThau_if_3_master.h5:1:900 \
image=/Volumes/Blue2/Data/i04-sethau-mad/SeThau_pk_2_master.h5:1:900 \
image=/Volumes/Blue2/Data/i04-sethau-mad/SeThau_pk_3_master.h5:1:900
```

**Comment by graeme-winter** [comment]
Suspect that this relates to the second splitting where we only get 3 sets of files not 6 - see #494 - which means that there are no data for later epochs

**Comment by graeme-winter** [comment]
OK, the `split_experiments` method of `DialsScalerHelper` knows nothing of the `by_wavelength` so expects (and encodes) 6 output files when only 3 appear here

**Comment by graeme-winter** [comment]
Branch to `scale-multipass-mad` to investigate

**Comment by graeme-winter** [comment]
To reproduce:

```
xia2 \
    image=$(dials.data get -q fumarase)/12287_1_E1_001.img:1:30 \
    image=$(dials.data get -q fumarase)/12287_1_E1_031.img:31:60 \
    image=$(dials.data get -q fumarase)/12287_1_E2_001.img:1:30 \
    image=$(dials.data get -q fumarase)/12287_1_E2_031.img:31:60
```
