### ISSUE TITLE
xia2 broken on Windows

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#594]
Seems the new method of installation is _actually broken_

```
C:\Users\graeme\data\i03-2021-run1-small\xia2-branch>xia2
Traceback (most recent call last):
  File "C:\Users\graeme\git\dials\conda_base\Scripts\xia2-script.py", line 33, in <module>
    sys.exit(load_entry_point('xia2', 'console_scripts', 'xia2')())
  File "C:\Users\graeme\git\dials\conda_base\Scripts\xia2-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\graeme\git\dials\conda_base\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\graeme\git\dials\conda_base\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\graeme\git\dials\modules\xia2\src\xia2\cli\xia2_main.py", line 7, in <module>
    from dials.util import Sorry
ModuleNotFoundError: No module named 'dials'
```

**Comment by Anthchirp** [comment]
"new method of installation" == ?

**Comment by graeme-winter** [comment]
i.e. what bootstrap now does in installing xia2, with the newfangled entry points done properly not the "Berkeley way" in libtbx.configure

**Comment by dagewa** [comment]
AFAICT the `xia2` dispatchers are no longer created at all on Windows, which I suppose is related to the issues with `dxtbx` dispatchers (https://github.com/cctbx/dxtbx/issues/393)
