### ISSUE TITLE
Multi crystal example data set gave some weird errors

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#60]
All appeared to work fine however:

```

Processing took 00h 20m 10s
Status: error ""
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

and

```
[gw56@cs04r-sc-com99-02 emma2]$ cat xia2.error
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 279, in run
    xinfo = xia2_main()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 254, in xia2_main
    generate_xia2_html(xinfo, filename='xia2.html')
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/html.py", line 35, in generate_xia2_html
    rst = get_xproject_rst(xinfo)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/html.py", line 130, in get_xproject_rst
    lines.extend(output_files_section(xproject))
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/html.py", line 414, in output_files_section
    html_file = make_logfile_html(logfile)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/html.py", line 48, in make_logfile_html
    tables = extract_loggraph_tables(logfile)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/html.py", line 613, in extract_loggraph_tables
    return data_plots.import_ccp4i_logfile(file_name=logfile)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/iotbx/data_plots.py", line 659, in import_ccp4i_logfile
    t.import_loggraph(loggraph)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/iotbx/data_plots.py", line 223, in import_loggraph
    self.add_row(fields)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/iotbx/data_plots.py", line 264, in add_row
    assert len(self.data) == len(row)
AssertionError
```

Worth noting that this was run with failover on, so the #sweeps may be different to the expected number.

**Comment by graeme-winter** [comment]
Have not seen this for a while; insufficient information in my own ticket to reproduce error / test if this fixed so closing
