### ISSUE TITLE
xia2.compare_merging_stats: setting anomalous=true breaks program

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#611]
```
Grey-Area cmp :) $ xia2.compare_merging_stats small_multiples=1 $(for d in Insulin_1_1 Insulin_3_1 Insulin_6_1 Insulin_7_1 Insulin_9_1 Insulin_10_1 Insulin_11_1 Insulin_12_1 ; do echo ../${d}/scaled.mtz; done) data_labels="Insulin_1_1 Insulin_3_1 Insulin_6_1 Insulin_7_1 Insulin_9_1 Insulin_10_1 Insulin_11_1 Insulin_12_1" anomalous=1
The following parameters have been modified:

anomalous = True
data_labels = "Insulin_1_1 Insulin_3_1 Insulin_6_1 Insulin_7_1 Insulin_9_1 Insulin_10_1 Insulin_11_1 Insulin_12_1"
small_multiples = True

../Insulin_3_1/scaled.mtz
../Insulin_1_1/scaled.mtz
../Insulin_7_1/scaled.mtz
../Insulin_10_1/scaled.mtz
../Insulin_6_1/scaled.mtz
../Insulin_11_1/scaled.mtz
../Insulin_9_1/scaled.mtz
../Insulin_12_1/scaled.mtz
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/concurrent/futures/process.py", line 208, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/multiprocessing/queues.py", line 372, in put
    obj = _ForkingPickler.dumps(obj)
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'cctbx.miller.anomalous_probability_plot'>: attribute lookup anomalous_probability_plot on cctbx.miller failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../conda_base/python.app/Contents/bin/xia2.compare_merging_stats", line 33, in <module>
    sys.exit(load_entry_point('xia2', 'console_scripts', 'xia2.compare_merging_stats')())
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/cli/compare_merging_stats.py", line 91, in run
    list(results),
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
_pickle.PicklingError: Can't pickle <class 'cctbx.miller.anomalous_probability_plot'>: attribute lookup anomalous_probability_plot on cctbx.miller failed
```

**Comment by rjgildea** [comment]
OK, this is likely because the mtz file name is printed when it is being read, which is within the function `get_merging_stats ()` that is run in parallel:
https://github.com/xia2/xia2/blob/7cf1b9cdafee6c2e74c48f559e32be023cb0e0eb/src/xia2/cli/compare_merging_stats.py#L114
https://github.com/xia2/xia2/blob/7cf1b9cdafee6c2e74c48f559e32be023cb0e0eb/src/xia2/cli/compare_merging_stats.py#L76-L88
I think this only reflects the order in which the mtz files are read, not the order of the results. You can easily confirm whether or not the results are affected by comparing with `nproc=1` (the default is `nproc=auto`).
