### ISSUE TITLE
Multiplex: does not exit cleanly when provided with serial still data

### ISSUE THREAD

**Issue by dagewa** [xia2/xia2#738]
This comes from a user testing the i2 interface. The user provided still shot integrated data rather than scans, but multiplex exits uncleanly in that case:

```
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/xia2/bin/xia2.multiplex", line 33, in <module>
    sys.exit(load_entry_point('xia2', 'console_scripts', 'xia2.multiplex')())
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/cli/multiplex.py", line 167, in run
    ScaleAndMerge.MultiCrystalScale(experiments, reflections_all, params)
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 295, in __init__
    self._data_manager = DataManager(experiments, reflections)
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/data_manager.py", line 30, in __init__
    self._set_batches()
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/data_manager.py", line 33, in _set_batches
    max_batches = max(e.scan.get_image_range()[1] for e in self._experiments)
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/data_manager.py", line 33, in <genexpr>
    max_batches = max(e.scan.get_image_range()[1] for e in self._experiments)
AttributeError: 'NoneType' object has no attribute 'get_image_range'
```

**Comment by jbeilstenedmands** [comment]
I think we are now in a place where we can make this just work, happy to assign myself to fixing this issue
