### ISSUE TITLE
Multiplex: failed with `IndexError`

### ISSUE THREAD

**Issue by dagewa** [xia2/xia2#749]
A multiplex job I was running failed with an `IndexError`. Here's the last part of the output:
```
Scaling cluster 64:
Cluster 64
  Number of datasets: 19
  Completeness: 100.0 %
  Multiplicity: 28.24
  Datasets:2,6,16,20,21,22,24,25,27,29,36,37,40,47,48,49,53,54,59
  height: 0.124786
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/xia2/bin/xia2.multiplex", line 33, in <module>
    sys.exit(load_entry_point('xia2', 'console_scripts', 'xia2.multiplex')())
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/cli/multiplex.py", line 167, in run
    ScaleAndMerge.MultiCrystalScale(experiments, reflections_all, params)
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 451, in __init__
    self._record_individual_report(
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 485, in _record_individual_report
    d = self._report_as_dict(report)
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/ScaleAndMerge.py", line 592, in _report_as_dict
    d.update(report.intensity_stats_plots())
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/Report/__init__.py", line 275, in intensity_stats_plots
    plotter = IntensityStatisticsPlots(
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/report/plots.py", line 298, in __init__
    self._xanalysis = xtriage_analyses(
  File "/home/fcx32934/sw/cctbx/modules/cctbx_project/mmtbx/scaling/xtriage.py", line 819, in __init__
    self.twin_results = twin_analyses.twin_analyses(
  File "/home/fcx32934/sw/cctbx/modules/cctbx_project/mmtbx/scaling/twin_analyses.py", line 2387, in __init__
    merge_data_and_guess_space_groups(
  File "/home/fcx32934/sw/cctbx/modules/cctbx_project/mmtbx/scaling/twin_analyses.py", line 2475, in merge_data_and_guess_space_groups
    normalizer = absolute_scaling.kernel_normalisation(tmp_ma, auto_kernel=True)
  File "/home/fcx32934/sw/cctbx/modules/cctbx_project/mmtbx/scaling/absolute_scaling.py", line 1001, in __init__
    self.kernel_width = d_star_sq_hkl[sort_permut[number]]-d_star_sq_low
IndexError: Index out of range.
```
Looks like this happened in xtriage, but would be nice if it was caught cleanly. The data are fairly grotty, if that makes a difference.

**Comment by jbeilstenedmands** [comment]
Looks like a genuine bug in mmtbx, I would be hesitant to blindly catch and ignore an IndexError in the calling code.

**Comment by dagewa** [comment]
Should be fixed by https://github.com/cctbx/cctbx_project/pull/904
