### ISSUE TITLE
xia2.cluster_analysis failure `KeyError: "Unknown column 'inverse_scale_factor'"`

### ISSUE THREAD

**Issue by dagewa** [xia2/xia2#774]
I wanted to try out https://github.com/xia2/xia2/pull/767, which as I understand it would give a plot that is analogous to XSCALE's table "CORRELATIONS BETWEEN INPUT DATA SETS AFTER CORRECTIONS". However it crashed. Perhaps I am using it wrongly?
```
$ xia2.cluster_analysis dials-exp_*/integrated.{expt,refl}
DIALS 3.dev.1077-gdcb5d7023
The following parameters have been modified:

input {
  experiments = dials-exp_14/integrated.expt
  experiments = dials-exp_16/integrated.expt
  experiments = dials-exp_23/integrated.expt
  experiments = dials-exp_27/integrated.expt
  reflections = dials-exp_14/integrated.refl
  reflections = dials-exp_16/integrated.refl
  reflections = dials-exp_23/integrated.refl
  reflections = dials-exp_27/integrated.refl
}

Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/xia2/bin/xia2.cluster_analysis", line 33, in <module>
    sys.exit(load_entry_point('xia2', 'console_scripts', 'xia2.cluster_analysis')())
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/cli/cluster_analysis.py", line 147, in run
    MCA = MultiCrystalReport(params, experiments, reflections_all)
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystalAnalysis.py", line 36, in __init__
    self._intensities_separate = self._data_manager.reflections_as_miller_arrays()
  File "/home/fcx32934/sw/cctbx/modules/xia2/src/xia2/Modules/MultiCrystal/data_manager.py", line 156, in reflections_as_miller_arrays
    sel &= r["inverse_scale_factor"] > 0
KeyError: "Unknown column 'inverse_scale_factor'"

```

**Comment by dagewa** [comment]
Ah okay, it works with scaled! Of course :roll_eyes: But probably it should not crash...

**Comment by jbeilstenedmands** [comment]
Fixed by https://github.com/xia2/xia2/pull/793 which supports running clustering analysis on integrated data.
