### ISSUE TITLE
Not running in Fedora 39

### ISSUE THREAD

**Issue by mysecondnameisdanger** [xia2/xia2#782]
I installed ccp4 (did the `find-missing-libs.sh` and `patch-rpaths.sh`), then installed `dials-v3-18-0-linux-x86_64`.
xia2 gives
```
msnid@fedora:~$ xia2
Traceback (most recent call last):
  File "/home/msnid/xstl/ccp4-8.0/bin/xia2", line 33, in <module>
    sys.exit(load_entry_point('xia2==3.8.6', 'console_scripts', 'xia2')())
  File "/home/msnid/xstl/ccp4-8.0/bin/xia2", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/importlib_metadata/api.py", line 71, in load
    module = import_module(match.group('module'))
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/xia2/cli/xia2_main.py", line 13, in <module>
    from xia2.Applications.xia2_helpers import process_one_sweep
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/xia2/Applications/xia2_helpers.py", line 7, in <module>
    from xia2.Driver.DriverFactory import DriverFactory
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/xia2/Driver/DriverFactory.py", line 4, in <module>
    from xia2.Driver.QSubDriver import QSubDriver
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/xia2/Driver/QSubDriver.py", line 8, in <module>
    from xia2.Handlers.Phil import PhilIndex
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/xia2/Handlers/Phil.py", line 1045, in <module>
    process_includes=True,
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/cctbx_project/iotbx/phil.py", line 84, in parse
    process_includes=process_includes)
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/cctbx_project/libtbx/phil/__init__.py", line 2198, in parse
    include_stack=include_stack)
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/cctbx_project/libtbx/phil/__init__.py", line 2007, in process_includes
    include_stack=include_stack))
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/cctbx_project/libtbx/phil/__init__.py", line 2007, in process_includes
    include_stack=include_stack))
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/cctbx_project/libtbx/phil/__init__.py", line 2007, in process_includes
    include_stack=include_stack))
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/cctbx_project/libtbx/phil/__init__.py", line 1999, in process_includes
    phil_path=phil_path).objects)
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/cctbx_project/libtbx/phil/__init__.py", line 2039, in process_include_scope
    where_str=object.where_str)
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/cctbx_project/libtbx/utils.py", line 1601, in __init__
    try: module = __import__(module_path)
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/dials/util/resolution_analysis.py", line 18, in <module>
    from dials.algorithms.scaling.scaling_library import determine_best_unit_cell
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/dials/algorithms/scaling/scaling_library.py", line 27, in <module>
    from dials.algorithms.scaling.model.model import KBScalingModel, PhysicalScalingModel
  File "/home/msnid/xstl/ccp4-8.0/lib/python3.7/site-packages/dials/algorithms/scaling/model/model.py", line 1431, in <module>
    ), "No models registered with dxtbx.scaling_model_ext entry point"
AssertionError: No models registered with dxtbx.scaling_model_ext entry point
msnid@fedora:~$ which xia2
~/xstl/ccp4-8.0/bin/xia2
msnid@fedora:~$ which dials.version
~/xstl/ccp4-8.0/bin/dials.version
msnid@fedora:~$ vim xstl/ccp4-8.0/bin/
Display all 659 possibilities? (y or n)
msnid@fedora:~$ vim xstl/ccp4-8.0/bin/ccp4.setup-sh 
msnid@fedora:~$ source .bashrc
msnid@fedora:~$ which xia2
~/xstl/dials-v3-18-0/build/bin/xia2
msnid@fedora:~$ which dials.version
~/xstl/dials-v3-18-0/build/bin/dials.version
msnid@fedora:~$ xia2
XIA2 3.18.0
An expert system for automated reduction of X-Ray
diffraction data from macromolecular crystals

Command-line options to xia2:
[pipeline=XXX] select processing pipeline, with XXX one of:
  3d    XDS, XSCALE
  3dii  XDS, XSCALE, using all images for autoindexing
  dials DIALS, scaling with DIALS
  dials-aimless DIALS, scaling with AIMLESS
[xinfo=foo.xinfo] or [/path/to/images]

[d_min=2.8] (say, applies to all sweeps)
[nproc=4] run on 4 processors (automatic)
[space_group=C2] (for example)
[unit_cell=50,50,50,90,90,90] (for example)
[reverse_phi=True]
[mosflm_beam_centre=x,y] (in mm, following the MOSFLM convention, applies to all sweeps)
[dials.fast_mode=True] for very fast processing
[atom=se] (say) - this is for xia2setup
[project=foo] (say) - this is for xia2setup
[crystal=bar] (say) - this is for xia2setup

Sensible command lines:
xia2 (pipeline=dials|3d|..) xinfo=foo.xinfo
xia2 project=foo crystal=bar (pipeline=dials|3d|..) /data/path
xia2 image=/data/path/segment_1_0001.cbf:1:900

```

I am changing line 87 in `ccp4.setup-sh` from `PATH=$CCP4/etc:$CCP4/bin:$PATH`  to `PATH=$PATH:$CCP4/etc:$CCP4/bin`
...

**Comment by dagewa** [comment]
Hi, please email ccp4@ccp4.ac.uk about the problem with CCP4's distribution of xia2.

In general, you should not edit `ccp4.setup-sh`. If you want to use xia2 from the DIALS v3.18.0 package you can source `ccp4.setup-sh` first and then the `dials_env.sh` script.

**Comment by mysecondnameisdanger** [comment]
Thanks I will send them an e-mail. I think it also does not work from the gui (`ccp4i2`). Gotta check. 
And...regarding the order of sourcing files... I have this in my `.bashrc`

```
# Phenix
source /home/murphy/xstl/phenix-dev-5246/phenix_env.sh
# Added by CCP4 package manager:
. '/home/murphy/xstl/ccp4-8.0/bin/ccp4.setup-sh'
# AutoProc
. /home/murphy/GPhL/autoPROC_snapshot_20240123/setup.sh
# XDS
export PATH=$PATH:/home/murphy/bin/linux_bin
# DIALS 3.18
# Otherwise 3.8
source /home/murphy/xstl/dials-v3-18-0/dials_env.sh
```
But I would get the `old` version of `dials` this way always... (I think.. )

Thanks again.
