### ISSUE TITLE
FileNotFoundError: COLSPOT.LP

### ISSUE THREAD

**Issue by wh277** [xia2/xia2#797]
I have installed dials and XDS in 2 computers. One can work with 3dii, but another could not work with 3dii. pipeline=dials-aimless is no problem.

Traceback (most recent call last):
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/cli/xia2_main.py", line 330, in run
    xia2_main()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/cli/xia2_main.py", line 242, in xia2_main
    sweep.get_integrater_intensities()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Schema/XSweep.py", line 825, in get_integrater_intensities
    reflections = self._get_integrater().get_integrater_intensities()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Schema/Interfaces/Integrater.py", line 577, in get_integrater_intensities
    self.integrate()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Schema/Interfaces/Integrater.py", line 520, in integrate
    self._integrate_prepare()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Modules/Integrater/XDSIntegrater.py", line 249, in _integrate_prepare
    self._intgr_refiner.get_refiner_payload(self.get_integrater_epoch())
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Schema/Interfaces/Refiner.py", line 238, in get_refiner_payload
    self.refine()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Schema/Interfaces/Refiner.py", line 224, in refine
    self._refine_prepare()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Modules/Refiner/XDSRefiner.py", line 27, in _refine_prepare
    experiments = idxr.get_indexer_experiment_list()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Schema/Interfaces/Indexer.py", line 712, in get_indexer_experiment_list
    self.index()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Schema/Interfaces/Indexer.py", line 436, in index
    self._index_prepare()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Modules/Indexer/XDSIndexerII.py", line 96, in _index_prepare
    super()._index_prepare()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Modules/Indexer/XDSIndexer.py", line 477, in _index_prepare
    colspot.run()
  File "/media/fy/A/sw/dials/dials-v3-20-0/modules/xia2/src/xia2/Wrappers/XDS/XDSColspot.py", line 157, in run
    shutil.copyfile(
  File "/media/fy/A/sw/dials/dials-v3-20-0/conda_base/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/media/fy/A/structrue/505-4/DEFAULT/SAD/SWEEP1/index/COLSPOT.LP'

**Comment by graeme-winter** [comment]
From the email you sent at the same time I can see that the issue here is that you have 104 threads available in your system where this fails, but XDS can cope with no more than 99 - if you run `xia2 nproc=96` say then this should work correctly

I need to add a patch to `xia2` to work around this

**Comment by wh277** [comment]
Thanks, it works now
