### ISSUE TITLE
Validate xia2 against new XDS BUILT=20240723

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#804]
```
 ***** XDS ***** (VERSION Jun 30, 2024  BUILT=20240723)  20-Aug-2024
 Author: Wolfgang Kabsch
 Copy licensed until 31-Aug-2025 to
  academic users for non-commercial applications
 No redistribution.

  !!! ERROR !!! CANNOT OPEN OR READ XDS.INP
```

[Release notes](https://xds.mr.mpg.de/html_doc/Release_Notes.html) suggest some things have changed, validate `xia2` behaviour

**Comment by graeme-winter** [comment]
```
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/export.py", line 699, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/export.py", line 692, in run
    exporter(params, experiments, reflections)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/export.py", line 386, in export_mtz
    export_mtz(
  File "/Users/graeme/git/dials/modules/dials/src/dials/util/export_mtz.py", line 727, in export_mtz
    add_batch_list(
  File "/Users/graeme/git/dials/modules/dials/src/dials/util/export_mtz.py", line 321, in add_batch_list
    batch.dataset_id = dataset_id
AttributeError: Please report this error to dials-support@lists.sourceforge.net: can't set attribute
```

**Comment by graeme-winter** [comment]
That was because I was running wrong pipeline 🤦‍♂️

With `pipeline=3dii` now get

```
Mosaic spread range: 0.067 0.077 0.091
Copied log file /private/tmp/b0rk/DEFAULT/NATIVE/SWEEP1/index/IDXREF.LP to /private/tmp/b0rk/LogFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1_INDEX.log
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/cli/xia2_main.py", line 330, in run
    xia2_main()
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/cli/xia2_main.py", line 242, in xia2_main
    sweep.get_integrater_intensities()
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/Schema/XSweep.py", line 825, in get_integrater_intensities
    reflections = self._get_integrater().get_integrater_intensities()
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/Schema/Interfaces/Integrater.py", line 577, in get_integrater_intensities
    self.integrate()
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/Schema/Interfaces/Integrater.py", line 549, in integrate
    self._intgr_hklout_raw = self._integrate()
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/Modules/Integrater/XDSIntegrater.py", line 377, in _integrate
    integrate.run()
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/Wrappers/XDS/XDSIntegrate.py", line 347, in run
    stats = parse_integrate_lp(
  File "/Users/graeme/git/dials/modules/xia2/src/xia2/Wrappers/XDS/XDSIntegrateHelpers.py", line 103, in parse_integrate_lp
    per_image_stats[image]["rmsd_pixel"] = rmsd_pixel
KeyError: 1

Error: 1
Please send the contents of xia2.txt, xia2-error.txt and xia2-debug.txt to:
xia2.support@gmail.com
```
