### ISSUE TITLE
Not (strictly) a xia2 issue

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#88]
Processing folder: ```/dls/i19-1/data/2016/cm14476-5/processed/KTP03_160_long/14```

```
For AUTOMATIC/DEFAULT/NATIVE                 Overall    Low     High
High resolution limit                           0.38    1.02    0.38
Low resolution limit                            6.41    6.41    0.38
Completeness                                  100.0   100.0   100.0
Multiplicity                                   11.6    20.5     3.2
I/sigma                                         9.4    18.4     3.5
Rmerge(I)                                     0.161   0.139   0.192
Rmeas(I)                                      0.166   0.143   0.230
Rpim(I)                                       0.040   0.033   0.124
CC half                                       0.997   0.993   0.946
Total observations                           106909   10913    1349
Total unique                                   9189     532     428
Assuming spacegroup: P n m a
Unit cell (with estimated std devs):
12.81643(3) 10.58763(2)  6.403264(15)
90.0        90.0        90.0         
mtz format:
Scaled reflections: /dls/i19-1/data/2016/cm14476-5/processed/KTP03_160_long/14/DataFiles/AUTOMATIC_DEFAULT_scaled.mtz
mtz_unmerged format:
Scaled reflections (NATIVE): /dls/i19-1/data/2016/cm14476-5/processed/KTP03_160_long/14/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz
sca format:
Scaled reflections (NATIVE): /dls/i19-1/data/2016/cm14476-5/processed/KTP03_160_long/14/DataFiles/AUTOMATIC_DEFAULT_scaled.sca
sca_unmerged format:
Scaled reflections (NATIVE): /dls/i19-1/data/2016/cm14476-5/processed/KTP03_160_long/14/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.sca
Processing took 00h 20m 45s
Status: error ""
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
```

```
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/xia2/command_line/xia2_main.py", line 279, in run
    xinfo = xia2_main()
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/xia2/command_line/xia2_main.py", line 254, in xia2_main
    generate_xia2_html(xinfo, filename='xia2.html')
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/xia2/command_line/html.py", line 35, in generate_xia2_html
    rst = get_xproject_rst(xinfo)
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/xia2/command_line/html.py", line 133, in get_xproject_rst
    lines.extend(output_files_section(xproject))
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/xia2/command_line/html.py", line 418, in output_files_section
    html_file = make_logfile_html(logfile)
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/xia2/command_line/html.py", line 51, in make_logfile_html
    tables = extract_loggraph_tables(logfile)
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/xia2/command_line/html.py", line 640, in extract_loggraph_tables
    return data_plots.import_ccp4i_logfile(file_name=logfile)
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/cctbx_project/iotbx/data_plots.py", line 659, in import_ccp4i_logfile
    t.import_loggraph(loggraph)
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/cctbx_project/iotbx/data_plots.py", line 223, in import_loggraph
    self.add_row(fields)
  File "/dls_sw/apps/dials/dials-v1-4-0/modules/cctbx_project/iotbx/data_plots.py", line 264, in add_row
    assert len(self.data) == len(row)
AssertionError
```

**Comment by Anthchirp** [comment]
caused by aimless.log

**Comment by Anthchirp** [comment]
ie.
```
import iotbx.data_plots
iotbx.data_plots.import_ccp4i_logfile('/dls/i19-1/data/2016/cm14476-5/processed/KTP03_160_long/14/LogFiles/AUTOMATIC_DEFAULT_aimless.log')
```

**Comment by Anthchirp** [comment]
"Reported" to cctbx via https://github.com/cctbx/cctbx_project/commit/f5a015c346176ae2b9e9a87a2aafcdfb2409d250

**Comment by Anthchirp** [comment]
Fixed by https://github.com/cctbx/cctbx_project/commit/63b9e85bd840353ee0057c2a8940339585157196
